// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/ledger/ent/idempotencykey"
	"opl-cloud/services/ledger/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IdempotencyKeyUpdate is the builder for updating IdempotencyKey entities.
type IdempotencyKeyUpdate struct {
	config
	hooks    []Hook
	mutation *IdempotencyKeyMutation
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (iku *IdempotencyKeyUpdate) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdate {
	iku.mutation.Where(ps...)
	return iku
}

// SetService sets the "service" field.
func (iku *IdempotencyKeyUpdate) SetService(s string) *IdempotencyKeyUpdate {
	iku.mutation.SetService(s)
	return iku
}

// SetNillableService sets the "service" field if the given value is not nil.
func (iku *IdempotencyKeyUpdate) SetNillableService(s *string) *IdempotencyKeyUpdate {
	if s != nil {
		iku.SetService(*s)
	}
	return iku
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (iku *IdempotencyKeyUpdate) SetIdempotencyKey(s string) *IdempotencyKeyUpdate {
	iku.mutation.SetIdempotencyKey(s)
	return iku
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (iku *IdempotencyKeyUpdate) SetNillableIdempotencyKey(s *string) *IdempotencyKeyUpdate {
	if s != nil {
		iku.SetIdempotencyKey(*s)
	}
	return iku
}

// SetRequestHash sets the "request_hash" field.
func (iku *IdempotencyKeyUpdate) SetRequestHash(s string) *IdempotencyKeyUpdate {
	iku.mutation.SetRequestHash(s)
	return iku
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (iku *IdempotencyKeyUpdate) SetNillableRequestHash(s *string) *IdempotencyKeyUpdate {
	if s != nil {
		iku.SetRequestHash(*s)
	}
	return iku
}

// SetResponseRef sets the "response_ref" field.
func (iku *IdempotencyKeyUpdate) SetResponseRef(s string) *IdempotencyKeyUpdate {
	iku.mutation.SetResponseRef(s)
	return iku
}

// SetNillableResponseRef sets the "response_ref" field if the given value is not nil.
func (iku *IdempotencyKeyUpdate) SetNillableResponseRef(s *string) *IdempotencyKeyUpdate {
	if s != nil {
		iku.SetResponseRef(*s)
	}
	return iku
}

// SetCreatedAt sets the "created_at" field.
func (iku *IdempotencyKeyUpdate) SetCreatedAt(t time.Time) *IdempotencyKeyUpdate {
	iku.mutation.SetCreatedAt(t)
	return iku
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (iku *IdempotencyKeyUpdate) SetNillableCreatedAt(t *time.Time) *IdempotencyKeyUpdate {
	if t != nil {
		iku.SetCreatedAt(*t)
	}
	return iku
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (iku *IdempotencyKeyUpdate) Mutation() *IdempotencyKeyMutation {
	return iku.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iku *IdempotencyKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iku.sqlSave, iku.mutation, iku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iku *IdempotencyKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := iku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iku *IdempotencyKeyUpdate) Exec(ctx context.Context) error {
	_, err := iku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iku *IdempotencyKeyUpdate) ExecX(ctx context.Context) {
	if err := iku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iku *IdempotencyKeyUpdate) check() error {
	if v, ok := iku.mutation.Service(); ok {
		if err := idempotencykey.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.service": %w`, err)}
		}
	}
	if v, ok := iku.mutation.IdempotencyKey(); ok {
		if err := idempotencykey.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.idempotency_key": %w`, err)}
		}
	}
	if v, ok := iku.mutation.RequestHash(); ok {
		if err := idempotencykey.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.request_hash": %w`, err)}
		}
	}
	return nil
}

func (iku *IdempotencyKeyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeString))
	if ps := iku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iku.mutation.Service(); ok {
		_spec.SetField(idempotencykey.FieldService, field.TypeString, value)
	}
	if value, ok := iku.mutation.IdempotencyKey(); ok {
		_spec.SetField(idempotencykey.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := iku.mutation.RequestHash(); ok {
		_spec.SetField(idempotencykey.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := iku.mutation.ResponseRef(); ok {
		_spec.SetField(idempotencykey.FieldResponseRef, field.TypeString, value)
	}
	if value, ok := iku.mutation.CreatedAt(); ok {
		_spec.SetField(idempotencykey.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iku.mutation.done = true
	return n, nil
}

// IdempotencyKeyUpdateOne is the builder for updating a single IdempotencyKey entity.
type IdempotencyKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdempotencyKeyMutation
}

// SetService sets the "service" field.
func (ikuo *IdempotencyKeyUpdateOne) SetService(s string) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetService(s)
	return ikuo
}

// SetNillableService sets the "service" field if the given value is not nil.
func (ikuo *IdempotencyKeyUpdateOne) SetNillableService(s *string) *IdempotencyKeyUpdateOne {
	if s != nil {
		ikuo.SetService(*s)
	}
	return ikuo
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (ikuo *IdempotencyKeyUpdateOne) SetIdempotencyKey(s string) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetIdempotencyKey(s)
	return ikuo
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (ikuo *IdempotencyKeyUpdateOne) SetNillableIdempotencyKey(s *string) *IdempotencyKeyUpdateOne {
	if s != nil {
		ikuo.SetIdempotencyKey(*s)
	}
	return ikuo
}

// SetRequestHash sets the "request_hash" field.
func (ikuo *IdempotencyKeyUpdateOne) SetRequestHash(s string) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetRequestHash(s)
	return ikuo
}

// SetNillableRequestHash sets the "request_hash" field if the given value is not nil.
func (ikuo *IdempotencyKeyUpdateOne) SetNillableRequestHash(s *string) *IdempotencyKeyUpdateOne {
	if s != nil {
		ikuo.SetRequestHash(*s)
	}
	return ikuo
}

// SetResponseRef sets the "response_ref" field.
func (ikuo *IdempotencyKeyUpdateOne) SetResponseRef(s string) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetResponseRef(s)
	return ikuo
}

// SetNillableResponseRef sets the "response_ref" field if the given value is not nil.
func (ikuo *IdempotencyKeyUpdateOne) SetNillableResponseRef(s *string) *IdempotencyKeyUpdateOne {
	if s != nil {
		ikuo.SetResponseRef(*s)
	}
	return ikuo
}

// SetCreatedAt sets the "created_at" field.
func (ikuo *IdempotencyKeyUpdateOne) SetCreatedAt(t time.Time) *IdempotencyKeyUpdateOne {
	ikuo.mutation.SetCreatedAt(t)
	return ikuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ikuo *IdempotencyKeyUpdateOne) SetNillableCreatedAt(t *time.Time) *IdempotencyKeyUpdateOne {
	if t != nil {
		ikuo.SetCreatedAt(*t)
	}
	return ikuo
}

// Mutation returns the IdempotencyKeyMutation object of the builder.
func (ikuo *IdempotencyKeyUpdateOne) Mutation() *IdempotencyKeyMutation {
	return ikuo.mutation
}

// Where appends a list predicates to the IdempotencyKeyUpdate builder.
func (ikuo *IdempotencyKeyUpdateOne) Where(ps ...predicate.IdempotencyKey) *IdempotencyKeyUpdateOne {
	ikuo.mutation.Where(ps...)
	return ikuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ikuo *IdempotencyKeyUpdateOne) Select(field string, fields ...string) *IdempotencyKeyUpdateOne {
	ikuo.fields = append([]string{field}, fields...)
	return ikuo
}

// Save executes the query and returns the updated IdempotencyKey entity.
func (ikuo *IdempotencyKeyUpdateOne) Save(ctx context.Context) (*IdempotencyKey, error) {
	return withHooks(ctx, ikuo.sqlSave, ikuo.mutation, ikuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ikuo *IdempotencyKeyUpdateOne) SaveX(ctx context.Context) *IdempotencyKey {
	node, err := ikuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ikuo *IdempotencyKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := ikuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ikuo *IdempotencyKeyUpdateOne) ExecX(ctx context.Context) {
	if err := ikuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ikuo *IdempotencyKeyUpdateOne) check() error {
	if v, ok := ikuo.mutation.Service(); ok {
		if err := idempotencykey.ServiceValidator(v); err != nil {
			return &ValidationError{Name: "service", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.service": %w`, err)}
		}
	}
	if v, ok := ikuo.mutation.IdempotencyKey(); ok {
		if err := idempotencykey.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.idempotency_key": %w`, err)}
		}
	}
	if v, ok := ikuo.mutation.RequestHash(); ok {
		if err := idempotencykey.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "IdempotencyKey.request_hash": %w`, err)}
		}
	}
	return nil
}

func (ikuo *IdempotencyKeyUpdateOne) sqlSave(ctx context.Context) (_node *IdempotencyKey, err error) {
	if err := ikuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(idempotencykey.Table, idempotencykey.Columns, sqlgraph.NewFieldSpec(idempotencykey.FieldID, field.TypeString))
	id, ok := ikuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IdempotencyKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ikuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, idempotencykey.FieldID)
		for _, f := range fields {
			if !idempotencykey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != idempotencykey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ikuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ikuo.mutation.Service(); ok {
		_spec.SetField(idempotencykey.FieldService, field.TypeString, value)
	}
	if value, ok := ikuo.mutation.IdempotencyKey(); ok {
		_spec.SetField(idempotencykey.FieldIdempotencyKey, field.TypeString, value)
	}
	if value, ok := ikuo.mutation.RequestHash(); ok {
		_spec.SetField(idempotencykey.FieldRequestHash, field.TypeString, value)
	}
	if value, ok := ikuo.mutation.ResponseRef(); ok {
		_spec.SetField(idempotencykey.FieldResponseRef, field.TypeString, value)
	}
	if value, ok := ikuo.mutation.CreatedAt(); ok {
		_spec.SetField(idempotencykey.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &IdempotencyKey{config: ikuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ikuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{idempotencykey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ikuo.mutation.done = true
	return _node, nil
}
