// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"opl-cloud/services/ledger/ent/resourcesettlement"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ResourceSettlement is the model entity for the ResourceSettlement schema.
type ResourceSettlement struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID string `json:"workspace_id,omitempty"`
	// ResourceType holds the value of the "resource_type" field.
	ResourceType string `json:"resource_type,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID string `json:"resource_id,omitempty"`
	// AmountCents holds the value of the "amount_cents" field.
	AmountCents int64 `json:"amount_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LedgerEntryID holds the value of the "ledger_entry_id" field.
	LedgerEntryID string `json:"ledger_entry_id,omitempty"`
	// WalletTransactionID holds the value of the "wallet_transaction_id" field.
	WalletTransactionID string `json:"wallet_transaction_id,omitempty"`
	// PricingVersion holds the value of the "pricing_version" field.
	PricingVersion string `json:"pricing_version,omitempty"`
	// PriceSnapshotJSON holds the value of the "price_snapshot_json" field.
	PriceSnapshotJSON string `json:"price_snapshot_json,omitempty"`
	// UsagePeriodStart holds the value of the "usage_period_start" field.
	UsagePeriodStart string `json:"usage_period_start,omitempty"`
	// UsagePeriodEnd holds the value of the "usage_period_end" field.
	UsagePeriodEnd string `json:"usage_period_end,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity float64 `json:"quantity,omitempty"`
	// Unit holds the value of the "unit" field.
	Unit string `json:"unit,omitempty"`
	// ProviderCostEvidenceRef holds the value of the "provider_cost_evidence_ref" field.
	ProviderCostEvidenceRef string `json:"provider_cost_evidence_ref,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceSettlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resourcesettlement.FieldQuantity:
			values[i] = new(sql.NullFloat64)
		case resourcesettlement.FieldAmountCents:
			values[i] = new(sql.NullInt64)
		case resourcesettlement.FieldID, resourcesettlement.FieldAccountID, resourcesettlement.FieldWorkspaceID, resourcesettlement.FieldResourceType, resourcesettlement.FieldResourceID, resourcesettlement.FieldCurrency, resourcesettlement.FieldStatus, resourcesettlement.FieldLedgerEntryID, resourcesettlement.FieldWalletTransactionID, resourcesettlement.FieldPricingVersion, resourcesettlement.FieldPriceSnapshotJSON, resourcesettlement.FieldUsagePeriodStart, resourcesettlement.FieldUsagePeriodEnd, resourcesettlement.FieldUnit, resourcesettlement.FieldProviderCostEvidenceRef, resourcesettlement.FieldIdempotencyKey, resourcesettlement.FieldRequestHash:
			values[i] = new(sql.NullString)
		case resourcesettlement.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceSettlement fields.
func (rs *ResourceSettlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resourcesettlement.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rs.ID = value.String
			}
		case resourcesettlement.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				rs.AccountID = value.String
			}
		case resourcesettlement.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				rs.WorkspaceID = value.String
			}
		case resourcesettlement.FieldResourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_type", values[i])
			} else if value.Valid {
				rs.ResourceType = value.String
			}
		case resourcesettlement.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				rs.ResourceID = value.String
			}
		case resourcesettlement.FieldAmountCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_cents", values[i])
			} else if value.Valid {
				rs.AmountCents = value.Int64
			}
		case resourcesettlement.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				rs.Currency = value.String
			}
		case resourcesettlement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				rs.Status = value.String
			}
		case resourcesettlement.FieldLedgerEntryID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ledger_entry_id", values[i])
			} else if value.Valid {
				rs.LedgerEntryID = value.String
			}
		case resourcesettlement.FieldWalletTransactionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_transaction_id", values[i])
			} else if value.Valid {
				rs.WalletTransactionID = value.String
			}
		case resourcesettlement.FieldPricingVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_version", values[i])
			} else if value.Valid {
				rs.PricingVersion = value.String
			}
		case resourcesettlement.FieldPriceSnapshotJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_snapshot_json", values[i])
			} else if value.Valid {
				rs.PriceSnapshotJSON = value.String
			}
		case resourcesettlement.FieldUsagePeriodStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_period_start", values[i])
			} else if value.Valid {
				rs.UsagePeriodStart = value.String
			}
		case resourcesettlement.FieldUsagePeriodEnd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_period_end", values[i])
			} else if value.Valid {
				rs.UsagePeriodEnd = value.String
			}
		case resourcesettlement.FieldQuantity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				rs.Quantity = value.Float64
			}
		case resourcesettlement.FieldUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit", values[i])
			} else if value.Valid {
				rs.Unit = value.String
			}
		case resourcesettlement.FieldProviderCostEvidenceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_cost_evidence_ref", values[i])
			} else if value.Valid {
				rs.ProviderCostEvidenceRef = value.String
			}
		case resourcesettlement.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				rs.IdempotencyKey = value.String
			}
		case resourcesettlement.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				rs.RequestHash = value.String
			}
		case resourcesettlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rs.CreatedAt = value.Time
			}
		default:
			rs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResourceSettlement.
// This includes values selected through modifiers, order, etc.
func (rs *ResourceSettlement) Value(name string) (ent.Value, error) {
	return rs.selectValues.Get(name)
}

// Update returns a builder for updating this ResourceSettlement.
// Note that you need to call ResourceSettlement.Unwrap() before calling this method if this ResourceSettlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (rs *ResourceSettlement) Update() *ResourceSettlementUpdateOne {
	return NewResourceSettlementClient(rs.config).UpdateOne(rs)
}

// Unwrap unwraps the ResourceSettlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rs *ResourceSettlement) Unwrap() *ResourceSettlement {
	_tx, ok := rs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceSettlement is not a transactional entity")
	}
	rs.config.driver = _tx.drv
	return rs
}

// String implements the fmt.Stringer.
func (rs *ResourceSettlement) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceSettlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rs.ID))
	builder.WriteString("account_id=")
	builder.WriteString(rs.AccountID)
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(rs.WorkspaceID)
	builder.WriteString(", ")
	builder.WriteString("resource_type=")
	builder.WriteString(rs.ResourceType)
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(rs.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("amount_cents=")
	builder.WriteString(fmt.Sprintf("%v", rs.AmountCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(rs.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(rs.Status)
	builder.WriteString(", ")
	builder.WriteString("ledger_entry_id=")
	builder.WriteString(rs.LedgerEntryID)
	builder.WriteString(", ")
	builder.WriteString("wallet_transaction_id=")
	builder.WriteString(rs.WalletTransactionID)
	builder.WriteString(", ")
	builder.WriteString("pricing_version=")
	builder.WriteString(rs.PricingVersion)
	builder.WriteString(", ")
	builder.WriteString("price_snapshot_json=")
	builder.WriteString(rs.PriceSnapshotJSON)
	builder.WriteString(", ")
	builder.WriteString("usage_period_start=")
	builder.WriteString(rs.UsagePeriodStart)
	builder.WriteString(", ")
	builder.WriteString("usage_period_end=")
	builder.WriteString(rs.UsagePeriodEnd)
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", rs.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit=")
	builder.WriteString(rs.Unit)
	builder.WriteString(", ")
	builder.WriteString("provider_cost_evidence_ref=")
	builder.WriteString(rs.ProviderCostEvidenceRef)
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(rs.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(rs.RequestHash)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rs.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ResourceSettlements is a parsable slice of ResourceSettlement.
type ResourceSettlements []*ResourceSettlement
