// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/ledger/ent/predicate"
	"opl-cloud/services/ledger/ent/wallet"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (wu *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetBalanceCents sets the "balance_cents" field.
func (wu *WalletUpdate) SetBalanceCents(i int64) *WalletUpdate {
	wu.mutation.ResetBalanceCents()
	wu.mutation.SetBalanceCents(i)
	return wu
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableBalanceCents(i *int64) *WalletUpdate {
	if i != nil {
		wu.SetBalanceCents(*i)
	}
	return wu
}

// AddBalanceCents adds i to the "balance_cents" field.
func (wu *WalletUpdate) AddBalanceCents(i int64) *WalletUpdate {
	wu.mutation.AddBalanceCents(i)
	return wu
}

// SetFrozenCents sets the "frozen_cents" field.
func (wu *WalletUpdate) SetFrozenCents(i int64) *WalletUpdate {
	wu.mutation.ResetFrozenCents()
	wu.mutation.SetFrozenCents(i)
	return wu
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableFrozenCents(i *int64) *WalletUpdate {
	if i != nil {
		wu.SetFrozenCents(*i)
	}
	return wu
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (wu *WalletUpdate) AddFrozenCents(i int64) *WalletUpdate {
	wu.mutation.AddFrozenCents(i)
	return wu
}

// SetAvailableCents sets the "available_cents" field.
func (wu *WalletUpdate) SetAvailableCents(i int64) *WalletUpdate {
	wu.mutation.ResetAvailableCents()
	wu.mutation.SetAvailableCents(i)
	return wu
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableAvailableCents(i *int64) *WalletUpdate {
	if i != nil {
		wu.SetAvailableCents(*i)
	}
	return wu
}

// AddAvailableCents adds i to the "available_cents" field.
func (wu *WalletUpdate) AddAvailableCents(i int64) *WalletUpdate {
	wu.mutation.AddAvailableCents(i)
	return wu
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (wu *WalletUpdate) SetTotalSpentCents(i int64) *WalletUpdate {
	wu.mutation.ResetTotalSpentCents()
	wu.mutation.SetTotalSpentCents(i)
	return wu
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableTotalSpentCents(i *int64) *WalletUpdate {
	if i != nil {
		wu.SetTotalSpentCents(*i)
	}
	return wu
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (wu *WalletUpdate) AddTotalSpentCents(i int64) *WalletUpdate {
	wu.mutation.AddTotalSpentCents(i)
	return wu
}

// SetCurrency sets the "currency" field.
func (wu *WalletUpdate) SetCurrency(s string) *WalletUpdate {
	wu.mutation.SetCurrency(s)
	return wu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableCurrency(s *string) *WalletUpdate {
	if s != nil {
		wu.SetCurrency(*s)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WalletUpdate) SetUpdatedAt(t time.Time) *WalletUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wu *WalletUpdate) SetNillableUpdatedAt(t *time.Time) *WalletUpdate {
	if t != nil {
		wu.SetUpdatedAt(*t)
	}
	return wu
}

// Mutation returns the WalletMutation object of the builder.
func (wu *WalletUpdate) Mutation() *WalletMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WalletUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WalletUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WalletUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wu *WalletUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.BalanceCents(); ok {
		_spec.SetField(wallet.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedBalanceCents(); ok {
		_spec.AddField(wallet.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.FrozenCents(); ok {
		_spec.SetField(wallet.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedFrozenCents(); ok {
		_spec.AddField(wallet.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AvailableCents(); ok {
		_spec.SetField(wallet.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedAvailableCents(); ok {
		_spec.AddField(wallet.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.TotalSpentCents(); ok {
		_spec.SetField(wallet.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(wallet.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.Currency(); ok {
		_spec.SetField(wallet.FieldCurrency, field.TypeString, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetBalanceCents sets the "balance_cents" field.
func (wuo *WalletUpdateOne) SetBalanceCents(i int64) *WalletUpdateOne {
	wuo.mutation.ResetBalanceCents()
	wuo.mutation.SetBalanceCents(i)
	return wuo
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableBalanceCents(i *int64) *WalletUpdateOne {
	if i != nil {
		wuo.SetBalanceCents(*i)
	}
	return wuo
}

// AddBalanceCents adds i to the "balance_cents" field.
func (wuo *WalletUpdateOne) AddBalanceCents(i int64) *WalletUpdateOne {
	wuo.mutation.AddBalanceCents(i)
	return wuo
}

// SetFrozenCents sets the "frozen_cents" field.
func (wuo *WalletUpdateOne) SetFrozenCents(i int64) *WalletUpdateOne {
	wuo.mutation.ResetFrozenCents()
	wuo.mutation.SetFrozenCents(i)
	return wuo
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableFrozenCents(i *int64) *WalletUpdateOne {
	if i != nil {
		wuo.SetFrozenCents(*i)
	}
	return wuo
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (wuo *WalletUpdateOne) AddFrozenCents(i int64) *WalletUpdateOne {
	wuo.mutation.AddFrozenCents(i)
	return wuo
}

// SetAvailableCents sets the "available_cents" field.
func (wuo *WalletUpdateOne) SetAvailableCents(i int64) *WalletUpdateOne {
	wuo.mutation.ResetAvailableCents()
	wuo.mutation.SetAvailableCents(i)
	return wuo
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableAvailableCents(i *int64) *WalletUpdateOne {
	if i != nil {
		wuo.SetAvailableCents(*i)
	}
	return wuo
}

// AddAvailableCents adds i to the "available_cents" field.
func (wuo *WalletUpdateOne) AddAvailableCents(i int64) *WalletUpdateOne {
	wuo.mutation.AddAvailableCents(i)
	return wuo
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (wuo *WalletUpdateOne) SetTotalSpentCents(i int64) *WalletUpdateOne {
	wuo.mutation.ResetTotalSpentCents()
	wuo.mutation.SetTotalSpentCents(i)
	return wuo
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableTotalSpentCents(i *int64) *WalletUpdateOne {
	if i != nil {
		wuo.SetTotalSpentCents(*i)
	}
	return wuo
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (wuo *WalletUpdateOne) AddTotalSpentCents(i int64) *WalletUpdateOne {
	wuo.mutation.AddTotalSpentCents(i)
	return wuo
}

// SetCurrency sets the "currency" field.
func (wuo *WalletUpdateOne) SetCurrency(s string) *WalletUpdateOne {
	wuo.mutation.SetCurrency(s)
	return wuo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableCurrency(s *string) *WalletUpdateOne {
	if s != nil {
		wuo.SetCurrency(*s)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WalletUpdateOne) SetUpdatedAt(t time.Time) *WalletUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wuo *WalletUpdateOne) SetNillableUpdatedAt(t *time.Time) *WalletUpdateOne {
	if t != nil {
		wuo.SetUpdatedAt(*t)
	}
	return wuo
}

// Mutation returns the WalletMutation object of the builder.
func (wuo *WalletUpdateOne) Mutation() *WalletMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (wuo *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Wallet entity.
func (wuo *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (wuo *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeString))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.BalanceCents(); ok {
		_spec.SetField(wallet.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedBalanceCents(); ok {
		_spec.AddField(wallet.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.FrozenCents(); ok {
		_spec.SetField(wallet.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedFrozenCents(); ok {
		_spec.AddField(wallet.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AvailableCents(); ok {
		_spec.SetField(wallet.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedAvailableCents(); ok {
		_spec.AddField(wallet.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.TotalSpentCents(); ok {
		_spec.SetField(wallet.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(wallet.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.Currency(); ok {
		_spec.SetField(wallet.FieldCurrency, field.TypeString, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Wallet{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
