// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/adminauditevent"
	"opl-cloud/services/control-plane/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminAuditEventUpdate is the builder for updating AdminAuditEvent entities.
type AdminAuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AdminAuditEventMutation
}

// Where appends a list predicates to the AdminAuditEventUpdate builder.
func (aaeu *AdminAuditEventUpdate) Where(ps ...predicate.AdminAuditEvent) *AdminAuditEventUpdate {
	aaeu.mutation.Where(ps...)
	return aaeu
}

// SetAccountID sets the "account_id" field.
func (aaeu *AdminAuditEventUpdate) SetAccountID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetAccountID(s)
	return aaeu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableAccountID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetAccountID(*s)
	}
	return aaeu
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (aaeu *AdminAuditEventUpdate) SetOwnerAccountID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetOwnerAccountID(s)
	return aaeu
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableOwnerAccountID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetOwnerAccountID(*s)
	}
	return aaeu
}

// SetOwnerUserID sets the "owner_user_id" field.
func (aaeu *AdminAuditEventUpdate) SetOwnerUserID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetOwnerUserID(s)
	return aaeu
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableOwnerUserID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetOwnerUserID(*s)
	}
	return aaeu
}

// SetUserID sets the "user_id" field.
func (aaeu *AdminAuditEventUpdate) SetUserID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetUserID(s)
	return aaeu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableUserID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetUserID(*s)
	}
	return aaeu
}

// SetEmail sets the "email" field.
func (aaeu *AdminAuditEventUpdate) SetEmail(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetEmail(s)
	return aaeu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableEmail(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetEmail(*s)
	}
	return aaeu
}

// SetRole sets the "role" field.
func (aaeu *AdminAuditEventUpdate) SetRole(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetRole(s)
	return aaeu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableRole(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetRole(*s)
	}
	return aaeu
}

// SetStatus sets the "status" field.
func (aaeu *AdminAuditEventUpdate) SetStatus(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetStatus(s)
	return aaeu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableStatus(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetStatus(*s)
	}
	return aaeu
}

// SetName sets the "name" field.
func (aaeu *AdminAuditEventUpdate) SetName(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetName(s)
	return aaeu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableName(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetName(*s)
	}
	return aaeu
}

// SetWorkspaceID sets the "workspace_id" field.
func (aaeu *AdminAuditEventUpdate) SetWorkspaceID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetWorkspaceID(s)
	return aaeu
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableWorkspaceID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetWorkspaceID(*s)
	}
	return aaeu
}

// SetResourceID sets the "resource_id" field.
func (aaeu *AdminAuditEventUpdate) SetResourceID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetResourceID(s)
	return aaeu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableResourceID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetResourceID(*s)
	}
	return aaeu
}

// SetResourceKind sets the "resource_kind" field.
func (aaeu *AdminAuditEventUpdate) SetResourceKind(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetResourceKind(s)
	return aaeu
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableResourceKind(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetResourceKind(*s)
	}
	return aaeu
}

// SetOperationID sets the "operation_id" field.
func (aaeu *AdminAuditEventUpdate) SetOperationID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetOperationID(s)
	return aaeu
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableOperationID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetOperationID(*s)
	}
	return aaeu
}

// SetProvider sets the "provider" field.
func (aaeu *AdminAuditEventUpdate) SetProvider(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetProvider(s)
	return aaeu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableProvider(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetProvider(*s)
	}
	return aaeu
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (aaeu *AdminAuditEventUpdate) SetProviderResourceID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetProviderResourceID(s)
	return aaeu
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableProviderResourceID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetProviderResourceID(*s)
	}
	return aaeu
}

// SetURL sets the "url" field.
func (aaeu *AdminAuditEventUpdate) SetURL(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetURL(s)
	return aaeu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableURL(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetURL(*s)
	}
	return aaeu
}

// SetHoldID sets the "hold_id" field.
func (aaeu *AdminAuditEventUpdate) SetHoldID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetHoldID(s)
	return aaeu
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableHoldID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetHoldID(*s)
	}
	return aaeu
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (aaeu *AdminAuditEventUpdate) SetHoldReleaseID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetHoldReleaseID(s)
	return aaeu
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableHoldReleaseID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetHoldReleaseID(*s)
	}
	return aaeu
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (aaeu *AdminAuditEventUpdate) SetLedgerEntryID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetLedgerEntryID(s)
	return aaeu
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableLedgerEntryID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetLedgerEntryID(*s)
	}
	return aaeu
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (aaeu *AdminAuditEventUpdate) SetWalletTransactionID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetWalletTransactionID(s)
	return aaeu
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableWalletTransactionID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetWalletTransactionID(*s)
	}
	return aaeu
}

// SetSettlementID sets the "settlement_id" field.
func (aaeu *AdminAuditEventUpdate) SetSettlementID(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetSettlementID(s)
	return aaeu
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableSettlementID(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetSettlementID(*s)
	}
	return aaeu
}

// SetPricingVersion sets the "pricing_version" field.
func (aaeu *AdminAuditEventUpdate) SetPricingVersion(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetPricingVersion(s)
	return aaeu
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillablePricingVersion(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetPricingVersion(*s)
	}
	return aaeu
}

// SetAmountCents sets the "amount_cents" field.
func (aaeu *AdminAuditEventUpdate) SetAmountCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetAmountCents()
	aaeu.mutation.SetAmountCents(i)
	return aaeu
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableAmountCents(i *int64) *AdminAuditEventUpdate {
	if i != nil {
		aaeu.SetAmountCents(*i)
	}
	return aaeu
}

// AddAmountCents adds i to the "amount_cents" field.
func (aaeu *AdminAuditEventUpdate) AddAmountCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.AddAmountCents(i)
	return aaeu
}

// SetBalanceCents sets the "balance_cents" field.
func (aaeu *AdminAuditEventUpdate) SetBalanceCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetBalanceCents()
	aaeu.mutation.SetBalanceCents(i)
	return aaeu
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableBalanceCents(i *int64) *AdminAuditEventUpdate {
	if i != nil {
		aaeu.SetBalanceCents(*i)
	}
	return aaeu
}

// AddBalanceCents adds i to the "balance_cents" field.
func (aaeu *AdminAuditEventUpdate) AddBalanceCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.AddBalanceCents(i)
	return aaeu
}

// SetFrozenCents sets the "frozen_cents" field.
func (aaeu *AdminAuditEventUpdate) SetFrozenCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetFrozenCents()
	aaeu.mutation.SetFrozenCents(i)
	return aaeu
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableFrozenCents(i *int64) *AdminAuditEventUpdate {
	if i != nil {
		aaeu.SetFrozenCents(*i)
	}
	return aaeu
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (aaeu *AdminAuditEventUpdate) AddFrozenCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.AddFrozenCents(i)
	return aaeu
}

// SetAvailableCents sets the "available_cents" field.
func (aaeu *AdminAuditEventUpdate) SetAvailableCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetAvailableCents()
	aaeu.mutation.SetAvailableCents(i)
	return aaeu
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableAvailableCents(i *int64) *AdminAuditEventUpdate {
	if i != nil {
		aaeu.SetAvailableCents(*i)
	}
	return aaeu
}

// AddAvailableCents adds i to the "available_cents" field.
func (aaeu *AdminAuditEventUpdate) AddAvailableCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.AddAvailableCents(i)
	return aaeu
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (aaeu *AdminAuditEventUpdate) SetTotalSpentCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetTotalSpentCents()
	aaeu.mutation.SetTotalSpentCents(i)
	return aaeu
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableTotalSpentCents(i *int64) *AdminAuditEventUpdate {
	if i != nil {
		aaeu.SetTotalSpentCents(*i)
	}
	return aaeu
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (aaeu *AdminAuditEventUpdate) AddTotalSpentCents(i int64) *AdminAuditEventUpdate {
	aaeu.mutation.AddTotalSpentCents(i)
	return aaeu
}

// SetQuantity sets the "quantity" field.
func (aaeu *AdminAuditEventUpdate) SetQuantity(f float64) *AdminAuditEventUpdate {
	aaeu.mutation.ResetQuantity()
	aaeu.mutation.SetQuantity(f)
	return aaeu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableQuantity(f *float64) *AdminAuditEventUpdate {
	if f != nil {
		aaeu.SetQuantity(*f)
	}
	return aaeu
}

// AddQuantity adds f to the "quantity" field.
func (aaeu *AdminAuditEventUpdate) AddQuantity(f float64) *AdminAuditEventUpdate {
	aaeu.mutation.AddQuantity(f)
	return aaeu
}

// SetUnit sets the "unit" field.
func (aaeu *AdminAuditEventUpdate) SetUnit(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetUnit(s)
	return aaeu
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableUnit(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetUnit(*s)
	}
	return aaeu
}

// SetReason sets the "reason" field.
func (aaeu *AdminAuditEventUpdate) SetReason(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetReason(s)
	return aaeu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableReason(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetReason(*s)
	}
	return aaeu
}

// SetResult sets the "result" field.
func (aaeu *AdminAuditEventUpdate) SetResult(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetResult(s)
	return aaeu
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableResult(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetResult(*s)
	}
	return aaeu
}

// SetSource sets the "source" field.
func (aaeu *AdminAuditEventUpdate) SetSource(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetSource(s)
	return aaeu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableSource(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetSource(*s)
	}
	return aaeu
}

// SetDirection sets the "direction" field.
func (aaeu *AdminAuditEventUpdate) SetDirection(s string) *AdminAuditEventUpdate {
	aaeu.mutation.SetDirection(s)
	return aaeu
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableDirection(s *string) *AdminAuditEventUpdate {
	if s != nil {
		aaeu.SetDirection(*s)
	}
	return aaeu
}

// SetCreatedAt sets the "created_at" field.
func (aaeu *AdminAuditEventUpdate) SetCreatedAt(t time.Time) *AdminAuditEventUpdate {
	aaeu.mutation.SetCreatedAt(t)
	return aaeu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableCreatedAt(t *time.Time) *AdminAuditEventUpdate {
	if t != nil {
		aaeu.SetCreatedAt(*t)
	}
	return aaeu
}

// SetUpdatedAt sets the "updated_at" field.
func (aaeu *AdminAuditEventUpdate) SetUpdatedAt(t time.Time) *AdminAuditEventUpdate {
	aaeu.mutation.SetUpdatedAt(t)
	return aaeu
}

// SetArchivedAt sets the "archived_at" field.
func (aaeu *AdminAuditEventUpdate) SetArchivedAt(t time.Time) *AdminAuditEventUpdate {
	aaeu.mutation.SetArchivedAt(t)
	return aaeu
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (aaeu *AdminAuditEventUpdate) SetNillableArchivedAt(t *time.Time) *AdminAuditEventUpdate {
	if t != nil {
		aaeu.SetArchivedAt(*t)
	}
	return aaeu
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (aaeu *AdminAuditEventUpdate) ClearArchivedAt() *AdminAuditEventUpdate {
	aaeu.mutation.ClearArchivedAt()
	return aaeu
}

// Mutation returns the AdminAuditEventMutation object of the builder.
func (aaeu *AdminAuditEventUpdate) Mutation() *AdminAuditEventMutation {
	return aaeu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aaeu *AdminAuditEventUpdate) Save(ctx context.Context) (int, error) {
	aaeu.defaults()
	return withHooks(ctx, aaeu.sqlSave, aaeu.mutation, aaeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aaeu *AdminAuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := aaeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aaeu *AdminAuditEventUpdate) Exec(ctx context.Context) error {
	_, err := aaeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aaeu *AdminAuditEventUpdate) ExecX(ctx context.Context) {
	if err := aaeu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aaeu *AdminAuditEventUpdate) defaults() {
	if _, ok := aaeu.mutation.UpdatedAt(); !ok {
		v := adminauditevent.UpdateDefaultUpdatedAt()
		aaeu.mutation.SetUpdatedAt(v)
	}
}

func (aaeu *AdminAuditEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminauditevent.Table, adminauditevent.Columns, sqlgraph.NewFieldSpec(adminauditevent.FieldID, field.TypeString))
	if ps := aaeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aaeu.mutation.AccountID(); ok {
		_spec.SetField(adminauditevent.FieldAccountID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.OwnerAccountID(); ok {
		_spec.SetField(adminauditevent.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.OwnerUserID(); ok {
		_spec.SetField(adminauditevent.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.UserID(); ok {
		_spec.SetField(adminauditevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Email(); ok {
		_spec.SetField(adminauditevent.FieldEmail, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Role(); ok {
		_spec.SetField(adminauditevent.FieldRole, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Status(); ok {
		_spec.SetField(adminauditevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Name(); ok {
		_spec.SetField(adminauditevent.FieldName, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.WorkspaceID(); ok {
		_spec.SetField(adminauditevent.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.ResourceID(); ok {
		_spec.SetField(adminauditevent.FieldResourceID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.ResourceKind(); ok {
		_spec.SetField(adminauditevent.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.OperationID(); ok {
		_spec.SetField(adminauditevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Provider(); ok {
		_spec.SetField(adminauditevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.ProviderResourceID(); ok {
		_spec.SetField(adminauditevent.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.URL(); ok {
		_spec.SetField(adminauditevent.FieldURL, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.HoldID(); ok {
		_spec.SetField(adminauditevent.FieldHoldID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.HoldReleaseID(); ok {
		_spec.SetField(adminauditevent.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.LedgerEntryID(); ok {
		_spec.SetField(adminauditevent.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.WalletTransactionID(); ok {
		_spec.SetField(adminauditevent.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.SettlementID(); ok {
		_spec.SetField(adminauditevent.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.PricingVersion(); ok {
		_spec.SetField(adminauditevent.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.AmountCents(); ok {
		_spec.SetField(adminauditevent.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AddedAmountCents(); ok {
		_spec.AddField(adminauditevent.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.BalanceCents(); ok {
		_spec.SetField(adminauditevent.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AddedBalanceCents(); ok {
		_spec.AddField(adminauditevent.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.FrozenCents(); ok {
		_spec.SetField(adminauditevent.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AddedFrozenCents(); ok {
		_spec.AddField(adminauditevent.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AvailableCents(); ok {
		_spec.SetField(adminauditevent.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AddedAvailableCents(); ok {
		_spec.AddField(adminauditevent.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.TotalSpentCents(); ok {
		_spec.SetField(adminauditevent.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(adminauditevent.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := aaeu.mutation.Quantity(); ok {
		_spec.SetField(adminauditevent.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := aaeu.mutation.AddedQuantity(); ok {
		_spec.AddField(adminauditevent.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := aaeu.mutation.Unit(); ok {
		_spec.SetField(adminauditevent.FieldUnit, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Reason(); ok {
		_spec.SetField(adminauditevent.FieldReason, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Result(); ok {
		_spec.SetField(adminauditevent.FieldResult, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Source(); ok {
		_spec.SetField(adminauditevent.FieldSource, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.Direction(); ok {
		_spec.SetField(adminauditevent.FieldDirection, field.TypeString, value)
	}
	if value, ok := aaeu.mutation.CreatedAt(); ok {
		_spec.SetField(adminauditevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := aaeu.mutation.UpdatedAt(); ok {
		_spec.SetField(adminauditevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aaeu.mutation.ArchivedAt(); ok {
		_spec.SetField(adminauditevent.FieldArchivedAt, field.TypeTime, value)
	}
	if aaeu.mutation.ArchivedAtCleared() {
		_spec.ClearField(adminauditevent.FieldArchivedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aaeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminauditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aaeu.mutation.done = true
	return n, nil
}

// AdminAuditEventUpdateOne is the builder for updating a single AdminAuditEvent entity.
type AdminAuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminAuditEventMutation
}

// SetAccountID sets the "account_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetAccountID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetAccountID(s)
	return aaeuo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableAccountID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetAccountID(*s)
	}
	return aaeuo
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetOwnerAccountID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetOwnerAccountID(s)
	return aaeuo
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableOwnerAccountID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetOwnerAccountID(*s)
	}
	return aaeuo
}

// SetOwnerUserID sets the "owner_user_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetOwnerUserID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetOwnerUserID(s)
	return aaeuo
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableOwnerUserID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetOwnerUserID(*s)
	}
	return aaeuo
}

// SetUserID sets the "user_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetUserID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetUserID(s)
	return aaeuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableUserID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetUserID(*s)
	}
	return aaeuo
}

// SetEmail sets the "email" field.
func (aaeuo *AdminAuditEventUpdateOne) SetEmail(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetEmail(s)
	return aaeuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableEmail(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetEmail(*s)
	}
	return aaeuo
}

// SetRole sets the "role" field.
func (aaeuo *AdminAuditEventUpdateOne) SetRole(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetRole(s)
	return aaeuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableRole(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetRole(*s)
	}
	return aaeuo
}

// SetStatus sets the "status" field.
func (aaeuo *AdminAuditEventUpdateOne) SetStatus(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetStatus(s)
	return aaeuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableStatus(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetStatus(*s)
	}
	return aaeuo
}

// SetName sets the "name" field.
func (aaeuo *AdminAuditEventUpdateOne) SetName(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetName(s)
	return aaeuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableName(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetName(*s)
	}
	return aaeuo
}

// SetWorkspaceID sets the "workspace_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetWorkspaceID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetWorkspaceID(s)
	return aaeuo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableWorkspaceID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetWorkspaceID(*s)
	}
	return aaeuo
}

// SetResourceID sets the "resource_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetResourceID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetResourceID(s)
	return aaeuo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableResourceID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetResourceID(*s)
	}
	return aaeuo
}

// SetResourceKind sets the "resource_kind" field.
func (aaeuo *AdminAuditEventUpdateOne) SetResourceKind(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetResourceKind(s)
	return aaeuo
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableResourceKind(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetResourceKind(*s)
	}
	return aaeuo
}

// SetOperationID sets the "operation_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetOperationID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetOperationID(s)
	return aaeuo
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableOperationID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetOperationID(*s)
	}
	return aaeuo
}

// SetProvider sets the "provider" field.
func (aaeuo *AdminAuditEventUpdateOne) SetProvider(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetProvider(s)
	return aaeuo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableProvider(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetProvider(*s)
	}
	return aaeuo
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetProviderResourceID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetProviderResourceID(s)
	return aaeuo
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableProviderResourceID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetProviderResourceID(*s)
	}
	return aaeuo
}

// SetURL sets the "url" field.
func (aaeuo *AdminAuditEventUpdateOne) SetURL(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetURL(s)
	return aaeuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableURL(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetURL(*s)
	}
	return aaeuo
}

// SetHoldID sets the "hold_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetHoldID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetHoldID(s)
	return aaeuo
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableHoldID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetHoldID(*s)
	}
	return aaeuo
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetHoldReleaseID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetHoldReleaseID(s)
	return aaeuo
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableHoldReleaseID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetHoldReleaseID(*s)
	}
	return aaeuo
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetLedgerEntryID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetLedgerEntryID(s)
	return aaeuo
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableLedgerEntryID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetLedgerEntryID(*s)
	}
	return aaeuo
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetWalletTransactionID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetWalletTransactionID(s)
	return aaeuo
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableWalletTransactionID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetWalletTransactionID(*s)
	}
	return aaeuo
}

// SetSettlementID sets the "settlement_id" field.
func (aaeuo *AdminAuditEventUpdateOne) SetSettlementID(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetSettlementID(s)
	return aaeuo
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableSettlementID(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetSettlementID(*s)
	}
	return aaeuo
}

// SetPricingVersion sets the "pricing_version" field.
func (aaeuo *AdminAuditEventUpdateOne) SetPricingVersion(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetPricingVersion(s)
	return aaeuo
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillablePricingVersion(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetPricingVersion(*s)
	}
	return aaeuo
}

// SetAmountCents sets the "amount_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) SetAmountCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetAmountCents()
	aaeuo.mutation.SetAmountCents(i)
	return aaeuo
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableAmountCents(i *int64) *AdminAuditEventUpdateOne {
	if i != nil {
		aaeuo.SetAmountCents(*i)
	}
	return aaeuo
}

// AddAmountCents adds i to the "amount_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) AddAmountCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddAmountCents(i)
	return aaeuo
}

// SetBalanceCents sets the "balance_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) SetBalanceCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetBalanceCents()
	aaeuo.mutation.SetBalanceCents(i)
	return aaeuo
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableBalanceCents(i *int64) *AdminAuditEventUpdateOne {
	if i != nil {
		aaeuo.SetBalanceCents(*i)
	}
	return aaeuo
}

// AddBalanceCents adds i to the "balance_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) AddBalanceCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddBalanceCents(i)
	return aaeuo
}

// SetFrozenCents sets the "frozen_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) SetFrozenCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetFrozenCents()
	aaeuo.mutation.SetFrozenCents(i)
	return aaeuo
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableFrozenCents(i *int64) *AdminAuditEventUpdateOne {
	if i != nil {
		aaeuo.SetFrozenCents(*i)
	}
	return aaeuo
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) AddFrozenCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddFrozenCents(i)
	return aaeuo
}

// SetAvailableCents sets the "available_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) SetAvailableCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetAvailableCents()
	aaeuo.mutation.SetAvailableCents(i)
	return aaeuo
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableAvailableCents(i *int64) *AdminAuditEventUpdateOne {
	if i != nil {
		aaeuo.SetAvailableCents(*i)
	}
	return aaeuo
}

// AddAvailableCents adds i to the "available_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) AddAvailableCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddAvailableCents(i)
	return aaeuo
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) SetTotalSpentCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetTotalSpentCents()
	aaeuo.mutation.SetTotalSpentCents(i)
	return aaeuo
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableTotalSpentCents(i *int64) *AdminAuditEventUpdateOne {
	if i != nil {
		aaeuo.SetTotalSpentCents(*i)
	}
	return aaeuo
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (aaeuo *AdminAuditEventUpdateOne) AddTotalSpentCents(i int64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddTotalSpentCents(i)
	return aaeuo
}

// SetQuantity sets the "quantity" field.
func (aaeuo *AdminAuditEventUpdateOne) SetQuantity(f float64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.ResetQuantity()
	aaeuo.mutation.SetQuantity(f)
	return aaeuo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableQuantity(f *float64) *AdminAuditEventUpdateOne {
	if f != nil {
		aaeuo.SetQuantity(*f)
	}
	return aaeuo
}

// AddQuantity adds f to the "quantity" field.
func (aaeuo *AdminAuditEventUpdateOne) AddQuantity(f float64) *AdminAuditEventUpdateOne {
	aaeuo.mutation.AddQuantity(f)
	return aaeuo
}

// SetUnit sets the "unit" field.
func (aaeuo *AdminAuditEventUpdateOne) SetUnit(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetUnit(s)
	return aaeuo
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableUnit(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetUnit(*s)
	}
	return aaeuo
}

// SetReason sets the "reason" field.
func (aaeuo *AdminAuditEventUpdateOne) SetReason(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetReason(s)
	return aaeuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableReason(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetReason(*s)
	}
	return aaeuo
}

// SetResult sets the "result" field.
func (aaeuo *AdminAuditEventUpdateOne) SetResult(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetResult(s)
	return aaeuo
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableResult(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetResult(*s)
	}
	return aaeuo
}

// SetSource sets the "source" field.
func (aaeuo *AdminAuditEventUpdateOne) SetSource(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetSource(s)
	return aaeuo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableSource(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetSource(*s)
	}
	return aaeuo
}

// SetDirection sets the "direction" field.
func (aaeuo *AdminAuditEventUpdateOne) SetDirection(s string) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetDirection(s)
	return aaeuo
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableDirection(s *string) *AdminAuditEventUpdateOne {
	if s != nil {
		aaeuo.SetDirection(*s)
	}
	return aaeuo
}

// SetCreatedAt sets the "created_at" field.
func (aaeuo *AdminAuditEventUpdateOne) SetCreatedAt(t time.Time) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetCreatedAt(t)
	return aaeuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableCreatedAt(t *time.Time) *AdminAuditEventUpdateOne {
	if t != nil {
		aaeuo.SetCreatedAt(*t)
	}
	return aaeuo
}

// SetUpdatedAt sets the "updated_at" field.
func (aaeuo *AdminAuditEventUpdateOne) SetUpdatedAt(t time.Time) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetUpdatedAt(t)
	return aaeuo
}

// SetArchivedAt sets the "archived_at" field.
func (aaeuo *AdminAuditEventUpdateOne) SetArchivedAt(t time.Time) *AdminAuditEventUpdateOne {
	aaeuo.mutation.SetArchivedAt(t)
	return aaeuo
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (aaeuo *AdminAuditEventUpdateOne) SetNillableArchivedAt(t *time.Time) *AdminAuditEventUpdateOne {
	if t != nil {
		aaeuo.SetArchivedAt(*t)
	}
	return aaeuo
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (aaeuo *AdminAuditEventUpdateOne) ClearArchivedAt() *AdminAuditEventUpdateOne {
	aaeuo.mutation.ClearArchivedAt()
	return aaeuo
}

// Mutation returns the AdminAuditEventMutation object of the builder.
func (aaeuo *AdminAuditEventUpdateOne) Mutation() *AdminAuditEventMutation {
	return aaeuo.mutation
}

// Where appends a list predicates to the AdminAuditEventUpdate builder.
func (aaeuo *AdminAuditEventUpdateOne) Where(ps ...predicate.AdminAuditEvent) *AdminAuditEventUpdateOne {
	aaeuo.mutation.Where(ps...)
	return aaeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aaeuo *AdminAuditEventUpdateOne) Select(field string, fields ...string) *AdminAuditEventUpdateOne {
	aaeuo.fields = append([]string{field}, fields...)
	return aaeuo
}

// Save executes the query and returns the updated AdminAuditEvent entity.
func (aaeuo *AdminAuditEventUpdateOne) Save(ctx context.Context) (*AdminAuditEvent, error) {
	aaeuo.defaults()
	return withHooks(ctx, aaeuo.sqlSave, aaeuo.mutation, aaeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aaeuo *AdminAuditEventUpdateOne) SaveX(ctx context.Context) *AdminAuditEvent {
	node, err := aaeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aaeuo *AdminAuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := aaeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aaeuo *AdminAuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := aaeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aaeuo *AdminAuditEventUpdateOne) defaults() {
	if _, ok := aaeuo.mutation.UpdatedAt(); !ok {
		v := adminauditevent.UpdateDefaultUpdatedAt()
		aaeuo.mutation.SetUpdatedAt(v)
	}
}

func (aaeuo *AdminAuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AdminAuditEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(adminauditevent.Table, adminauditevent.Columns, sqlgraph.NewFieldSpec(adminauditevent.FieldID, field.TypeString))
	id, ok := aaeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminAuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aaeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminauditevent.FieldID)
		for _, f := range fields {
			if !adminauditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminauditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aaeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aaeuo.mutation.AccountID(); ok {
		_spec.SetField(adminauditevent.FieldAccountID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.OwnerAccountID(); ok {
		_spec.SetField(adminauditevent.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.OwnerUserID(); ok {
		_spec.SetField(adminauditevent.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.UserID(); ok {
		_spec.SetField(adminauditevent.FieldUserID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Email(); ok {
		_spec.SetField(adminauditevent.FieldEmail, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Role(); ok {
		_spec.SetField(adminauditevent.FieldRole, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Status(); ok {
		_spec.SetField(adminauditevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Name(); ok {
		_spec.SetField(adminauditevent.FieldName, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.WorkspaceID(); ok {
		_spec.SetField(adminauditevent.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.ResourceID(); ok {
		_spec.SetField(adminauditevent.FieldResourceID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.ResourceKind(); ok {
		_spec.SetField(adminauditevent.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.OperationID(); ok {
		_spec.SetField(adminauditevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Provider(); ok {
		_spec.SetField(adminauditevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.ProviderResourceID(); ok {
		_spec.SetField(adminauditevent.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.URL(); ok {
		_spec.SetField(adminauditevent.FieldURL, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.HoldID(); ok {
		_spec.SetField(adminauditevent.FieldHoldID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.HoldReleaseID(); ok {
		_spec.SetField(adminauditevent.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.LedgerEntryID(); ok {
		_spec.SetField(adminauditevent.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.WalletTransactionID(); ok {
		_spec.SetField(adminauditevent.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.SettlementID(); ok {
		_spec.SetField(adminauditevent.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.PricingVersion(); ok {
		_spec.SetField(adminauditevent.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.AmountCents(); ok {
		_spec.SetField(adminauditevent.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AddedAmountCents(); ok {
		_spec.AddField(adminauditevent.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.BalanceCents(); ok {
		_spec.SetField(adminauditevent.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AddedBalanceCents(); ok {
		_spec.AddField(adminauditevent.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.FrozenCents(); ok {
		_spec.SetField(adminauditevent.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AddedFrozenCents(); ok {
		_spec.AddField(adminauditevent.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AvailableCents(); ok {
		_spec.SetField(adminauditevent.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AddedAvailableCents(); ok {
		_spec.AddField(adminauditevent.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.TotalSpentCents(); ok {
		_spec.SetField(adminauditevent.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(adminauditevent.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := aaeuo.mutation.Quantity(); ok {
		_spec.SetField(adminauditevent.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := aaeuo.mutation.AddedQuantity(); ok {
		_spec.AddField(adminauditevent.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := aaeuo.mutation.Unit(); ok {
		_spec.SetField(adminauditevent.FieldUnit, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Reason(); ok {
		_spec.SetField(adminauditevent.FieldReason, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Result(); ok {
		_spec.SetField(adminauditevent.FieldResult, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Source(); ok {
		_spec.SetField(adminauditevent.FieldSource, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.Direction(); ok {
		_spec.SetField(adminauditevent.FieldDirection, field.TypeString, value)
	}
	if value, ok := aaeuo.mutation.CreatedAt(); ok {
		_spec.SetField(adminauditevent.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := aaeuo.mutation.UpdatedAt(); ok {
		_spec.SetField(adminauditevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aaeuo.mutation.ArchivedAt(); ok {
		_spec.SetField(adminauditevent.FieldArchivedAt, field.TypeTime, value)
	}
	if aaeuo.mutation.ArchivedAtCleared() {
		_spec.ClearField(adminauditevent.FieldArchivedAt, field.TypeTime)
	}
	_node = &AdminAuditEvent{config: aaeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aaeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminauditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aaeuo.mutation.done = true
	return _node, nil
}
