// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/archivedcomputeallocation"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArchivedComputeAllocationCreate is the builder for creating a ArchivedComputeAllocation entity.
type ArchivedComputeAllocationCreate struct {
	config
	mutation *ArchivedComputeAllocationMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (acac *ArchivedComputeAllocationCreate) SetAccountID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetAccountID(s)
	return acac
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableAccountID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetAccountID(*s)
	}
	return acac
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (acac *ArchivedComputeAllocationCreate) SetOwnerAccountID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetOwnerAccountID(s)
	return acac
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableOwnerAccountID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetOwnerAccountID(*s)
	}
	return acac
}

// SetOwnerUserID sets the "owner_user_id" field.
func (acac *ArchivedComputeAllocationCreate) SetOwnerUserID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetOwnerUserID(s)
	return acac
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableOwnerUserID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetOwnerUserID(*s)
	}
	return acac
}

// SetUserID sets the "user_id" field.
func (acac *ArchivedComputeAllocationCreate) SetUserID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetUserID(s)
	return acac
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableUserID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetUserID(*s)
	}
	return acac
}

// SetEmail sets the "email" field.
func (acac *ArchivedComputeAllocationCreate) SetEmail(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetEmail(s)
	return acac
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableEmail(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetEmail(*s)
	}
	return acac
}

// SetRole sets the "role" field.
func (acac *ArchivedComputeAllocationCreate) SetRole(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetRole(s)
	return acac
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableRole(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetRole(*s)
	}
	return acac
}

// SetStatus sets the "status" field.
func (acac *ArchivedComputeAllocationCreate) SetStatus(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetStatus(s)
	return acac
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableStatus(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetStatus(*s)
	}
	return acac
}

// SetName sets the "name" field.
func (acac *ArchivedComputeAllocationCreate) SetName(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetName(s)
	return acac
}

// SetNillableName sets the "name" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableName(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetName(*s)
	}
	return acac
}

// SetWorkspaceID sets the "workspace_id" field.
func (acac *ArchivedComputeAllocationCreate) SetWorkspaceID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetWorkspaceID(s)
	return acac
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableWorkspaceID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetWorkspaceID(*s)
	}
	return acac
}

// SetResourceID sets the "resource_id" field.
func (acac *ArchivedComputeAllocationCreate) SetResourceID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetResourceID(s)
	return acac
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableResourceID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetResourceID(*s)
	}
	return acac
}

// SetResourceKind sets the "resource_kind" field.
func (acac *ArchivedComputeAllocationCreate) SetResourceKind(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetResourceKind(s)
	return acac
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableResourceKind(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetResourceKind(*s)
	}
	return acac
}

// SetOperationID sets the "operation_id" field.
func (acac *ArchivedComputeAllocationCreate) SetOperationID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetOperationID(s)
	return acac
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableOperationID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetOperationID(*s)
	}
	return acac
}

// SetProvider sets the "provider" field.
func (acac *ArchivedComputeAllocationCreate) SetProvider(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetProvider(s)
	return acac
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableProvider(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetProvider(*s)
	}
	return acac
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (acac *ArchivedComputeAllocationCreate) SetProviderResourceID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetProviderResourceID(s)
	return acac
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableProviderResourceID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetProviderResourceID(*s)
	}
	return acac
}

// SetURL sets the "url" field.
func (acac *ArchivedComputeAllocationCreate) SetURL(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetURL(s)
	return acac
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableURL(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetURL(*s)
	}
	return acac
}

// SetHoldID sets the "hold_id" field.
func (acac *ArchivedComputeAllocationCreate) SetHoldID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetHoldID(s)
	return acac
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableHoldID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetHoldID(*s)
	}
	return acac
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (acac *ArchivedComputeAllocationCreate) SetHoldReleaseID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetHoldReleaseID(s)
	return acac
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableHoldReleaseID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetHoldReleaseID(*s)
	}
	return acac
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (acac *ArchivedComputeAllocationCreate) SetLedgerEntryID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetLedgerEntryID(s)
	return acac
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableLedgerEntryID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetLedgerEntryID(*s)
	}
	return acac
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (acac *ArchivedComputeAllocationCreate) SetWalletTransactionID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetWalletTransactionID(s)
	return acac
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableWalletTransactionID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetWalletTransactionID(*s)
	}
	return acac
}

// SetSettlementID sets the "settlement_id" field.
func (acac *ArchivedComputeAllocationCreate) SetSettlementID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetSettlementID(s)
	return acac
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableSettlementID(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetSettlementID(*s)
	}
	return acac
}

// SetPricingVersion sets the "pricing_version" field.
func (acac *ArchivedComputeAllocationCreate) SetPricingVersion(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetPricingVersion(s)
	return acac
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillablePricingVersion(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetPricingVersion(*s)
	}
	return acac
}

// SetAmountCents sets the "amount_cents" field.
func (acac *ArchivedComputeAllocationCreate) SetAmountCents(i int64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetAmountCents(i)
	return acac
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableAmountCents(i *int64) *ArchivedComputeAllocationCreate {
	if i != nil {
		acac.SetAmountCents(*i)
	}
	return acac
}

// SetBalanceCents sets the "balance_cents" field.
func (acac *ArchivedComputeAllocationCreate) SetBalanceCents(i int64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetBalanceCents(i)
	return acac
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableBalanceCents(i *int64) *ArchivedComputeAllocationCreate {
	if i != nil {
		acac.SetBalanceCents(*i)
	}
	return acac
}

// SetFrozenCents sets the "frozen_cents" field.
func (acac *ArchivedComputeAllocationCreate) SetFrozenCents(i int64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetFrozenCents(i)
	return acac
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableFrozenCents(i *int64) *ArchivedComputeAllocationCreate {
	if i != nil {
		acac.SetFrozenCents(*i)
	}
	return acac
}

// SetAvailableCents sets the "available_cents" field.
func (acac *ArchivedComputeAllocationCreate) SetAvailableCents(i int64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetAvailableCents(i)
	return acac
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableAvailableCents(i *int64) *ArchivedComputeAllocationCreate {
	if i != nil {
		acac.SetAvailableCents(*i)
	}
	return acac
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (acac *ArchivedComputeAllocationCreate) SetTotalSpentCents(i int64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetTotalSpentCents(i)
	return acac
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableTotalSpentCents(i *int64) *ArchivedComputeAllocationCreate {
	if i != nil {
		acac.SetTotalSpentCents(*i)
	}
	return acac
}

// SetQuantity sets the "quantity" field.
func (acac *ArchivedComputeAllocationCreate) SetQuantity(f float64) *ArchivedComputeAllocationCreate {
	acac.mutation.SetQuantity(f)
	return acac
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableQuantity(f *float64) *ArchivedComputeAllocationCreate {
	if f != nil {
		acac.SetQuantity(*f)
	}
	return acac
}

// SetUnit sets the "unit" field.
func (acac *ArchivedComputeAllocationCreate) SetUnit(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetUnit(s)
	return acac
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableUnit(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetUnit(*s)
	}
	return acac
}

// SetReason sets the "reason" field.
func (acac *ArchivedComputeAllocationCreate) SetReason(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetReason(s)
	return acac
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableReason(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetReason(*s)
	}
	return acac
}

// SetResult sets the "result" field.
func (acac *ArchivedComputeAllocationCreate) SetResult(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetResult(s)
	return acac
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableResult(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetResult(*s)
	}
	return acac
}

// SetSource sets the "source" field.
func (acac *ArchivedComputeAllocationCreate) SetSource(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetSource(s)
	return acac
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableSource(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetSource(*s)
	}
	return acac
}

// SetDirection sets the "direction" field.
func (acac *ArchivedComputeAllocationCreate) SetDirection(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetDirection(s)
	return acac
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableDirection(s *string) *ArchivedComputeAllocationCreate {
	if s != nil {
		acac.SetDirection(*s)
	}
	return acac
}

// SetCreatedAt sets the "created_at" field.
func (acac *ArchivedComputeAllocationCreate) SetCreatedAt(t time.Time) *ArchivedComputeAllocationCreate {
	acac.mutation.SetCreatedAt(t)
	return acac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableCreatedAt(t *time.Time) *ArchivedComputeAllocationCreate {
	if t != nil {
		acac.SetCreatedAt(*t)
	}
	return acac
}

// SetUpdatedAt sets the "updated_at" field.
func (acac *ArchivedComputeAllocationCreate) SetUpdatedAt(t time.Time) *ArchivedComputeAllocationCreate {
	acac.mutation.SetUpdatedAt(t)
	return acac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableUpdatedAt(t *time.Time) *ArchivedComputeAllocationCreate {
	if t != nil {
		acac.SetUpdatedAt(*t)
	}
	return acac
}

// SetArchivedAt sets the "archived_at" field.
func (acac *ArchivedComputeAllocationCreate) SetArchivedAt(t time.Time) *ArchivedComputeAllocationCreate {
	acac.mutation.SetArchivedAt(t)
	return acac
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (acac *ArchivedComputeAllocationCreate) SetNillableArchivedAt(t *time.Time) *ArchivedComputeAllocationCreate {
	if t != nil {
		acac.SetArchivedAt(*t)
	}
	return acac
}

// SetID sets the "id" field.
func (acac *ArchivedComputeAllocationCreate) SetID(s string) *ArchivedComputeAllocationCreate {
	acac.mutation.SetID(s)
	return acac
}

// Mutation returns the ArchivedComputeAllocationMutation object of the builder.
func (acac *ArchivedComputeAllocationCreate) Mutation() *ArchivedComputeAllocationMutation {
	return acac.mutation
}

// Save creates the ArchivedComputeAllocation in the database.
func (acac *ArchivedComputeAllocationCreate) Save(ctx context.Context) (*ArchivedComputeAllocation, error) {
	acac.defaults()
	return withHooks(ctx, acac.sqlSave, acac.mutation, acac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (acac *ArchivedComputeAllocationCreate) SaveX(ctx context.Context) *ArchivedComputeAllocation {
	v, err := acac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acac *ArchivedComputeAllocationCreate) Exec(ctx context.Context) error {
	_, err := acac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acac *ArchivedComputeAllocationCreate) ExecX(ctx context.Context) {
	if err := acac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (acac *ArchivedComputeAllocationCreate) defaults() {
	if _, ok := acac.mutation.AccountID(); !ok {
		v := archivedcomputeallocation.DefaultAccountID
		acac.mutation.SetAccountID(v)
	}
	if _, ok := acac.mutation.OwnerAccountID(); !ok {
		v := archivedcomputeallocation.DefaultOwnerAccountID
		acac.mutation.SetOwnerAccountID(v)
	}
	if _, ok := acac.mutation.OwnerUserID(); !ok {
		v := archivedcomputeallocation.DefaultOwnerUserID
		acac.mutation.SetOwnerUserID(v)
	}
	if _, ok := acac.mutation.UserID(); !ok {
		v := archivedcomputeallocation.DefaultUserID
		acac.mutation.SetUserID(v)
	}
	if _, ok := acac.mutation.Email(); !ok {
		v := archivedcomputeallocation.DefaultEmail
		acac.mutation.SetEmail(v)
	}
	if _, ok := acac.mutation.Role(); !ok {
		v := archivedcomputeallocation.DefaultRole
		acac.mutation.SetRole(v)
	}
	if _, ok := acac.mutation.Status(); !ok {
		v := archivedcomputeallocation.DefaultStatus
		acac.mutation.SetStatus(v)
	}
	if _, ok := acac.mutation.Name(); !ok {
		v := archivedcomputeallocation.DefaultName
		acac.mutation.SetName(v)
	}
	if _, ok := acac.mutation.WorkspaceID(); !ok {
		v := archivedcomputeallocation.DefaultWorkspaceID
		acac.mutation.SetWorkspaceID(v)
	}
	if _, ok := acac.mutation.ResourceID(); !ok {
		v := archivedcomputeallocation.DefaultResourceID
		acac.mutation.SetResourceID(v)
	}
	if _, ok := acac.mutation.ResourceKind(); !ok {
		v := archivedcomputeallocation.DefaultResourceKind
		acac.mutation.SetResourceKind(v)
	}
	if _, ok := acac.mutation.OperationID(); !ok {
		v := archivedcomputeallocation.DefaultOperationID
		acac.mutation.SetOperationID(v)
	}
	if _, ok := acac.mutation.Provider(); !ok {
		v := archivedcomputeallocation.DefaultProvider
		acac.mutation.SetProvider(v)
	}
	if _, ok := acac.mutation.ProviderResourceID(); !ok {
		v := archivedcomputeallocation.DefaultProviderResourceID
		acac.mutation.SetProviderResourceID(v)
	}
	if _, ok := acac.mutation.URL(); !ok {
		v := archivedcomputeallocation.DefaultURL
		acac.mutation.SetURL(v)
	}
	if _, ok := acac.mutation.HoldID(); !ok {
		v := archivedcomputeallocation.DefaultHoldID
		acac.mutation.SetHoldID(v)
	}
	if _, ok := acac.mutation.HoldReleaseID(); !ok {
		v := archivedcomputeallocation.DefaultHoldReleaseID
		acac.mutation.SetHoldReleaseID(v)
	}
	if _, ok := acac.mutation.LedgerEntryID(); !ok {
		v := archivedcomputeallocation.DefaultLedgerEntryID
		acac.mutation.SetLedgerEntryID(v)
	}
	if _, ok := acac.mutation.WalletTransactionID(); !ok {
		v := archivedcomputeallocation.DefaultWalletTransactionID
		acac.mutation.SetWalletTransactionID(v)
	}
	if _, ok := acac.mutation.SettlementID(); !ok {
		v := archivedcomputeallocation.DefaultSettlementID
		acac.mutation.SetSettlementID(v)
	}
	if _, ok := acac.mutation.PricingVersion(); !ok {
		v := archivedcomputeallocation.DefaultPricingVersion
		acac.mutation.SetPricingVersion(v)
	}
	if _, ok := acac.mutation.AmountCents(); !ok {
		v := archivedcomputeallocation.DefaultAmountCents
		acac.mutation.SetAmountCents(v)
	}
	if _, ok := acac.mutation.BalanceCents(); !ok {
		v := archivedcomputeallocation.DefaultBalanceCents
		acac.mutation.SetBalanceCents(v)
	}
	if _, ok := acac.mutation.FrozenCents(); !ok {
		v := archivedcomputeallocation.DefaultFrozenCents
		acac.mutation.SetFrozenCents(v)
	}
	if _, ok := acac.mutation.AvailableCents(); !ok {
		v := archivedcomputeallocation.DefaultAvailableCents
		acac.mutation.SetAvailableCents(v)
	}
	if _, ok := acac.mutation.TotalSpentCents(); !ok {
		v := archivedcomputeallocation.DefaultTotalSpentCents
		acac.mutation.SetTotalSpentCents(v)
	}
	if _, ok := acac.mutation.Quantity(); !ok {
		v := archivedcomputeallocation.DefaultQuantity
		acac.mutation.SetQuantity(v)
	}
	if _, ok := acac.mutation.Unit(); !ok {
		v := archivedcomputeallocation.DefaultUnit
		acac.mutation.SetUnit(v)
	}
	if _, ok := acac.mutation.Reason(); !ok {
		v := archivedcomputeallocation.DefaultReason
		acac.mutation.SetReason(v)
	}
	if _, ok := acac.mutation.Result(); !ok {
		v := archivedcomputeallocation.DefaultResult
		acac.mutation.SetResult(v)
	}
	if _, ok := acac.mutation.Source(); !ok {
		v := archivedcomputeallocation.DefaultSource
		acac.mutation.SetSource(v)
	}
	if _, ok := acac.mutation.Direction(); !ok {
		v := archivedcomputeallocation.DefaultDirection
		acac.mutation.SetDirection(v)
	}
	if _, ok := acac.mutation.CreatedAt(); !ok {
		v := archivedcomputeallocation.DefaultCreatedAt()
		acac.mutation.SetCreatedAt(v)
	}
	if _, ok := acac.mutation.UpdatedAt(); !ok {
		v := archivedcomputeallocation.DefaultUpdatedAt()
		acac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (acac *ArchivedComputeAllocationCreate) check() error {
	if _, ok := acac.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.account_id"`)}
	}
	if _, ok := acac.mutation.OwnerAccountID(); !ok {
		return &ValidationError{Name: "owner_account_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.owner_account_id"`)}
	}
	if _, ok := acac.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.owner_user_id"`)}
	}
	if _, ok := acac.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.user_id"`)}
	}
	if _, ok := acac.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.email"`)}
	}
	if _, ok := acac.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.role"`)}
	}
	if _, ok := acac.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.status"`)}
	}
	if _, ok := acac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.name"`)}
	}
	if _, ok := acac.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.workspace_id"`)}
	}
	if _, ok := acac.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.resource_id"`)}
	}
	if _, ok := acac.mutation.ResourceKind(); !ok {
		return &ValidationError{Name: "resource_kind", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.resource_kind"`)}
	}
	if _, ok := acac.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.operation_id"`)}
	}
	if _, ok := acac.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.provider"`)}
	}
	if _, ok := acac.mutation.ProviderResourceID(); !ok {
		return &ValidationError{Name: "provider_resource_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.provider_resource_id"`)}
	}
	if _, ok := acac.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.url"`)}
	}
	if _, ok := acac.mutation.HoldID(); !ok {
		return &ValidationError{Name: "hold_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.hold_id"`)}
	}
	if _, ok := acac.mutation.HoldReleaseID(); !ok {
		return &ValidationError{Name: "hold_release_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.hold_release_id"`)}
	}
	if _, ok := acac.mutation.LedgerEntryID(); !ok {
		return &ValidationError{Name: "ledger_entry_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.ledger_entry_id"`)}
	}
	if _, ok := acac.mutation.WalletTransactionID(); !ok {
		return &ValidationError{Name: "wallet_transaction_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.wallet_transaction_id"`)}
	}
	if _, ok := acac.mutation.SettlementID(); !ok {
		return &ValidationError{Name: "settlement_id", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.settlement_id"`)}
	}
	if _, ok := acac.mutation.PricingVersion(); !ok {
		return &ValidationError{Name: "pricing_version", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.pricing_version"`)}
	}
	if _, ok := acac.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.amount_cents"`)}
	}
	if _, ok := acac.mutation.BalanceCents(); !ok {
		return &ValidationError{Name: "balance_cents", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.balance_cents"`)}
	}
	if _, ok := acac.mutation.FrozenCents(); !ok {
		return &ValidationError{Name: "frozen_cents", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.frozen_cents"`)}
	}
	if _, ok := acac.mutation.AvailableCents(); !ok {
		return &ValidationError{Name: "available_cents", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.available_cents"`)}
	}
	if _, ok := acac.mutation.TotalSpentCents(); !ok {
		return &ValidationError{Name: "total_spent_cents", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.total_spent_cents"`)}
	}
	if _, ok := acac.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.quantity"`)}
	}
	if _, ok := acac.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.unit"`)}
	}
	if _, ok := acac.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.reason"`)}
	}
	if _, ok := acac.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.result"`)}
	}
	if _, ok := acac.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.source"`)}
	}
	if _, ok := acac.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.direction"`)}
	}
	if _, ok := acac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.created_at"`)}
	}
	if _, ok := acac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArchivedComputeAllocation.updated_at"`)}
	}
	if v, ok := acac.mutation.ID(); ok {
		if err := archivedcomputeallocation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ArchivedComputeAllocation.id": %w`, err)}
		}
	}
	return nil
}

func (acac *ArchivedComputeAllocationCreate) sqlSave(ctx context.Context) (*ArchivedComputeAllocation, error) {
	if err := acac.check(); err != nil {
		return nil, err
	}
	_node, _spec := acac.createSpec()
	if err := sqlgraph.CreateNode(ctx, acac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ArchivedComputeAllocation.ID type: %T", _spec.ID.Value)
		}
	}
	acac.mutation.id = &_node.ID
	acac.mutation.done = true
	return _node, nil
}

func (acac *ArchivedComputeAllocationCreate) createSpec() (*ArchivedComputeAllocation, *sqlgraph.CreateSpec) {
	var (
		_node = &ArchivedComputeAllocation{config: acac.config}
		_spec = sqlgraph.NewCreateSpec(archivedcomputeallocation.Table, sqlgraph.NewFieldSpec(archivedcomputeallocation.FieldID, field.TypeString))
	)
	if id, ok := acac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := acac.mutation.AccountID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := acac.mutation.OwnerAccountID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldOwnerAccountID, field.TypeString, value)
		_node.OwnerAccountID = value
	}
	if value, ok := acac.mutation.OwnerUserID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := acac.mutation.UserID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := acac.mutation.Email(); ok {
		_spec.SetField(archivedcomputeallocation.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := acac.mutation.Role(); ok {
		_spec.SetField(archivedcomputeallocation.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := acac.mutation.Status(); ok {
		_spec.SetField(archivedcomputeallocation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := acac.mutation.Name(); ok {
		_spec.SetField(archivedcomputeallocation.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := acac.mutation.WorkspaceID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := acac.mutation.ResourceID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := acac.mutation.ResourceKind(); ok {
		_spec.SetField(archivedcomputeallocation.FieldResourceKind, field.TypeString, value)
		_node.ResourceKind = value
	}
	if value, ok := acac.mutation.OperationID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := acac.mutation.Provider(); ok {
		_spec.SetField(archivedcomputeallocation.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := acac.mutation.ProviderResourceID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldProviderResourceID, field.TypeString, value)
		_node.ProviderResourceID = value
	}
	if value, ok := acac.mutation.URL(); ok {
		_spec.SetField(archivedcomputeallocation.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := acac.mutation.HoldID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldHoldID, field.TypeString, value)
		_node.HoldID = value
	}
	if value, ok := acac.mutation.HoldReleaseID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldHoldReleaseID, field.TypeString, value)
		_node.HoldReleaseID = value
	}
	if value, ok := acac.mutation.LedgerEntryID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldLedgerEntryID, field.TypeString, value)
		_node.LedgerEntryID = value
	}
	if value, ok := acac.mutation.WalletTransactionID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldWalletTransactionID, field.TypeString, value)
		_node.WalletTransactionID = value
	}
	if value, ok := acac.mutation.SettlementID(); ok {
		_spec.SetField(archivedcomputeallocation.FieldSettlementID, field.TypeString, value)
		_node.SettlementID = value
	}
	if value, ok := acac.mutation.PricingVersion(); ok {
		_spec.SetField(archivedcomputeallocation.FieldPricingVersion, field.TypeString, value)
		_node.PricingVersion = value
	}
	if value, ok := acac.mutation.AmountCents(); ok {
		_spec.SetField(archivedcomputeallocation.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := acac.mutation.BalanceCents(); ok {
		_spec.SetField(archivedcomputeallocation.FieldBalanceCents, field.TypeInt64, value)
		_node.BalanceCents = value
	}
	if value, ok := acac.mutation.FrozenCents(); ok {
		_spec.SetField(archivedcomputeallocation.FieldFrozenCents, field.TypeInt64, value)
		_node.FrozenCents = value
	}
	if value, ok := acac.mutation.AvailableCents(); ok {
		_spec.SetField(archivedcomputeallocation.FieldAvailableCents, field.TypeInt64, value)
		_node.AvailableCents = value
	}
	if value, ok := acac.mutation.TotalSpentCents(); ok {
		_spec.SetField(archivedcomputeallocation.FieldTotalSpentCents, field.TypeInt64, value)
		_node.TotalSpentCents = value
	}
	if value, ok := acac.mutation.Quantity(); ok {
		_spec.SetField(archivedcomputeallocation.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := acac.mutation.Unit(); ok {
		_spec.SetField(archivedcomputeallocation.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := acac.mutation.Reason(); ok {
		_spec.SetField(archivedcomputeallocation.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := acac.mutation.Result(); ok {
		_spec.SetField(archivedcomputeallocation.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := acac.mutation.Source(); ok {
		_spec.SetField(archivedcomputeallocation.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := acac.mutation.Direction(); ok {
		_spec.SetField(archivedcomputeallocation.FieldDirection, field.TypeString, value)
		_node.Direction = value
	}
	if value, ok := acac.mutation.CreatedAt(); ok {
		_spec.SetField(archivedcomputeallocation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := acac.mutation.UpdatedAt(); ok {
		_spec.SetField(archivedcomputeallocation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := acac.mutation.ArchivedAt(); ok {
		_spec.SetField(archivedcomputeallocation.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = &value
	}
	return _node, _spec
}

// ArchivedComputeAllocationCreateBulk is the builder for creating many ArchivedComputeAllocation entities in bulk.
type ArchivedComputeAllocationCreateBulk struct {
	config
	err      error
	builders []*ArchivedComputeAllocationCreate
}

// Save creates the ArchivedComputeAllocation entities in the database.
func (acacb *ArchivedComputeAllocationCreateBulk) Save(ctx context.Context) ([]*ArchivedComputeAllocation, error) {
	if acacb.err != nil {
		return nil, acacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acacb.builders))
	nodes := make([]*ArchivedComputeAllocation, len(acacb.builders))
	mutators := make([]Mutator, len(acacb.builders))
	for i := range acacb.builders {
		func(i int, root context.Context) {
			builder := acacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArchivedComputeAllocationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acacb *ArchivedComputeAllocationCreateBulk) SaveX(ctx context.Context) []*ArchivedComputeAllocation {
	v, err := acacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acacb *ArchivedComputeAllocationCreateBulk) Exec(ctx context.Context) error {
	_, err := acacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acacb *ArchivedComputeAllocationCreateBulk) ExecX(ctx context.Context) {
	if err := acacb.Exec(ctx); err != nil {
		panic(err)
	}
}
