// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/productione2erecord"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductionE2ERecordDelete is the builder for deleting a ProductionE2ERecord entity.
type ProductionE2ERecordDelete struct {
	config
	hooks    []Hook
	mutation *ProductionE2ERecordMutation
}

// Where appends a list predicates to the ProductionE2ERecordDelete builder.
func (perd *ProductionE2ERecordDelete) Where(ps ...predicate.ProductionE2ERecord) *ProductionE2ERecordDelete {
	perd.mutation.Where(ps...)
	return perd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (perd *ProductionE2ERecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, perd.sqlExec, perd.mutation, perd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (perd *ProductionE2ERecordDelete) ExecX(ctx context.Context) int {
	n, err := perd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (perd *ProductionE2ERecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(productione2erecord.Table, sqlgraph.NewFieldSpec(productione2erecord.FieldID, field.TypeString))
	if ps := perd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, perd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	perd.mutation.done = true
	return affected, err
}

// ProductionE2ERecordDeleteOne is the builder for deleting a single ProductionE2ERecord entity.
type ProductionE2ERecordDeleteOne struct {
	perd *ProductionE2ERecordDelete
}

// Where appends a list predicates to the ProductionE2ERecordDelete builder.
func (perdo *ProductionE2ERecordDeleteOne) Where(ps ...predicate.ProductionE2ERecord) *ProductionE2ERecordDeleteOne {
	perdo.perd.mutation.Where(ps...)
	return perdo
}

// Exec executes the deletion query.
func (perdo *ProductionE2ERecordDeleteOne) Exec(ctx context.Context) error {
	n, err := perdo.perd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productione2erecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (perdo *ProductionE2ERecordDeleteOne) ExecX(ctx context.Context) {
	if err := perdo.Exec(ctx); err != nil {
		panic(err)
	}
}
