// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/storageattachment"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StorageAttachmentUpdate is the builder for updating StorageAttachment entities.
type StorageAttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *StorageAttachmentMutation
}

// Where appends a list predicates to the StorageAttachmentUpdate builder.
func (sau *StorageAttachmentUpdate) Where(ps ...predicate.StorageAttachment) *StorageAttachmentUpdate {
	sau.mutation.Where(ps...)
	return sau
}

// SetAccountID sets the "account_id" field.
func (sau *StorageAttachmentUpdate) SetAccountID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetAccountID(s)
	return sau
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableAccountID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetAccountID(*s)
	}
	return sau
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (sau *StorageAttachmentUpdate) SetOwnerAccountID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetOwnerAccountID(s)
	return sau
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableOwnerAccountID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetOwnerAccountID(*s)
	}
	return sau
}

// SetOwnerUserID sets the "owner_user_id" field.
func (sau *StorageAttachmentUpdate) SetOwnerUserID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetOwnerUserID(s)
	return sau
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableOwnerUserID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetOwnerUserID(*s)
	}
	return sau
}

// SetUserID sets the "user_id" field.
func (sau *StorageAttachmentUpdate) SetUserID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetUserID(s)
	return sau
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableUserID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetUserID(*s)
	}
	return sau
}

// SetEmail sets the "email" field.
func (sau *StorageAttachmentUpdate) SetEmail(s string) *StorageAttachmentUpdate {
	sau.mutation.SetEmail(s)
	return sau
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableEmail(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetEmail(*s)
	}
	return sau
}

// SetRole sets the "role" field.
func (sau *StorageAttachmentUpdate) SetRole(s string) *StorageAttachmentUpdate {
	sau.mutation.SetRole(s)
	return sau
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableRole(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetRole(*s)
	}
	return sau
}

// SetStatus sets the "status" field.
func (sau *StorageAttachmentUpdate) SetStatus(s string) *StorageAttachmentUpdate {
	sau.mutation.SetStatus(s)
	return sau
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableStatus(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetStatus(*s)
	}
	return sau
}

// SetName sets the "name" field.
func (sau *StorageAttachmentUpdate) SetName(s string) *StorageAttachmentUpdate {
	sau.mutation.SetName(s)
	return sau
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableName(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetName(*s)
	}
	return sau
}

// SetWorkspaceID sets the "workspace_id" field.
func (sau *StorageAttachmentUpdate) SetWorkspaceID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetWorkspaceID(s)
	return sau
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableWorkspaceID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetWorkspaceID(*s)
	}
	return sau
}

// SetResourceID sets the "resource_id" field.
func (sau *StorageAttachmentUpdate) SetResourceID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetResourceID(s)
	return sau
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableResourceID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetResourceID(*s)
	}
	return sau
}

// SetResourceKind sets the "resource_kind" field.
func (sau *StorageAttachmentUpdate) SetResourceKind(s string) *StorageAttachmentUpdate {
	sau.mutation.SetResourceKind(s)
	return sau
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableResourceKind(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetResourceKind(*s)
	}
	return sau
}

// SetOperationID sets the "operation_id" field.
func (sau *StorageAttachmentUpdate) SetOperationID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetOperationID(s)
	return sau
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableOperationID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetOperationID(*s)
	}
	return sau
}

// SetProvider sets the "provider" field.
func (sau *StorageAttachmentUpdate) SetProvider(s string) *StorageAttachmentUpdate {
	sau.mutation.SetProvider(s)
	return sau
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableProvider(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetProvider(*s)
	}
	return sau
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (sau *StorageAttachmentUpdate) SetProviderResourceID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetProviderResourceID(s)
	return sau
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableProviderResourceID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetProviderResourceID(*s)
	}
	return sau
}

// SetURL sets the "url" field.
func (sau *StorageAttachmentUpdate) SetURL(s string) *StorageAttachmentUpdate {
	sau.mutation.SetURL(s)
	return sau
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableURL(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetURL(*s)
	}
	return sau
}

// SetHoldID sets the "hold_id" field.
func (sau *StorageAttachmentUpdate) SetHoldID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetHoldID(s)
	return sau
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableHoldID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetHoldID(*s)
	}
	return sau
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (sau *StorageAttachmentUpdate) SetHoldReleaseID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetHoldReleaseID(s)
	return sau
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableHoldReleaseID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetHoldReleaseID(*s)
	}
	return sau
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (sau *StorageAttachmentUpdate) SetLedgerEntryID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetLedgerEntryID(s)
	return sau
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableLedgerEntryID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetLedgerEntryID(*s)
	}
	return sau
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (sau *StorageAttachmentUpdate) SetWalletTransactionID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetWalletTransactionID(s)
	return sau
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableWalletTransactionID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetWalletTransactionID(*s)
	}
	return sau
}

// SetSettlementID sets the "settlement_id" field.
func (sau *StorageAttachmentUpdate) SetSettlementID(s string) *StorageAttachmentUpdate {
	sau.mutation.SetSettlementID(s)
	return sau
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableSettlementID(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetSettlementID(*s)
	}
	return sau
}

// SetPricingVersion sets the "pricing_version" field.
func (sau *StorageAttachmentUpdate) SetPricingVersion(s string) *StorageAttachmentUpdate {
	sau.mutation.SetPricingVersion(s)
	return sau
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillablePricingVersion(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetPricingVersion(*s)
	}
	return sau
}

// SetAmountCents sets the "amount_cents" field.
func (sau *StorageAttachmentUpdate) SetAmountCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.ResetAmountCents()
	sau.mutation.SetAmountCents(i)
	return sau
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableAmountCents(i *int64) *StorageAttachmentUpdate {
	if i != nil {
		sau.SetAmountCents(*i)
	}
	return sau
}

// AddAmountCents adds i to the "amount_cents" field.
func (sau *StorageAttachmentUpdate) AddAmountCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.AddAmountCents(i)
	return sau
}

// SetBalanceCents sets the "balance_cents" field.
func (sau *StorageAttachmentUpdate) SetBalanceCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.ResetBalanceCents()
	sau.mutation.SetBalanceCents(i)
	return sau
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableBalanceCents(i *int64) *StorageAttachmentUpdate {
	if i != nil {
		sau.SetBalanceCents(*i)
	}
	return sau
}

// AddBalanceCents adds i to the "balance_cents" field.
func (sau *StorageAttachmentUpdate) AddBalanceCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.AddBalanceCents(i)
	return sau
}

// SetFrozenCents sets the "frozen_cents" field.
func (sau *StorageAttachmentUpdate) SetFrozenCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.ResetFrozenCents()
	sau.mutation.SetFrozenCents(i)
	return sau
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableFrozenCents(i *int64) *StorageAttachmentUpdate {
	if i != nil {
		sau.SetFrozenCents(*i)
	}
	return sau
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (sau *StorageAttachmentUpdate) AddFrozenCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.AddFrozenCents(i)
	return sau
}

// SetAvailableCents sets the "available_cents" field.
func (sau *StorageAttachmentUpdate) SetAvailableCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.ResetAvailableCents()
	sau.mutation.SetAvailableCents(i)
	return sau
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableAvailableCents(i *int64) *StorageAttachmentUpdate {
	if i != nil {
		sau.SetAvailableCents(*i)
	}
	return sau
}

// AddAvailableCents adds i to the "available_cents" field.
func (sau *StorageAttachmentUpdate) AddAvailableCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.AddAvailableCents(i)
	return sau
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (sau *StorageAttachmentUpdate) SetTotalSpentCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.ResetTotalSpentCents()
	sau.mutation.SetTotalSpentCents(i)
	return sau
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableTotalSpentCents(i *int64) *StorageAttachmentUpdate {
	if i != nil {
		sau.SetTotalSpentCents(*i)
	}
	return sau
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (sau *StorageAttachmentUpdate) AddTotalSpentCents(i int64) *StorageAttachmentUpdate {
	sau.mutation.AddTotalSpentCents(i)
	return sau
}

// SetQuantity sets the "quantity" field.
func (sau *StorageAttachmentUpdate) SetQuantity(f float64) *StorageAttachmentUpdate {
	sau.mutation.ResetQuantity()
	sau.mutation.SetQuantity(f)
	return sau
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableQuantity(f *float64) *StorageAttachmentUpdate {
	if f != nil {
		sau.SetQuantity(*f)
	}
	return sau
}

// AddQuantity adds f to the "quantity" field.
func (sau *StorageAttachmentUpdate) AddQuantity(f float64) *StorageAttachmentUpdate {
	sau.mutation.AddQuantity(f)
	return sau
}

// SetUnit sets the "unit" field.
func (sau *StorageAttachmentUpdate) SetUnit(s string) *StorageAttachmentUpdate {
	sau.mutation.SetUnit(s)
	return sau
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableUnit(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetUnit(*s)
	}
	return sau
}

// SetReason sets the "reason" field.
func (sau *StorageAttachmentUpdate) SetReason(s string) *StorageAttachmentUpdate {
	sau.mutation.SetReason(s)
	return sau
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableReason(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetReason(*s)
	}
	return sau
}

// SetResult sets the "result" field.
func (sau *StorageAttachmentUpdate) SetResult(s string) *StorageAttachmentUpdate {
	sau.mutation.SetResult(s)
	return sau
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableResult(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetResult(*s)
	}
	return sau
}

// SetSource sets the "source" field.
func (sau *StorageAttachmentUpdate) SetSource(s string) *StorageAttachmentUpdate {
	sau.mutation.SetSource(s)
	return sau
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableSource(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetSource(*s)
	}
	return sau
}

// SetDirection sets the "direction" field.
func (sau *StorageAttachmentUpdate) SetDirection(s string) *StorageAttachmentUpdate {
	sau.mutation.SetDirection(s)
	return sau
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableDirection(s *string) *StorageAttachmentUpdate {
	if s != nil {
		sau.SetDirection(*s)
	}
	return sau
}

// SetCreatedAt sets the "created_at" field.
func (sau *StorageAttachmentUpdate) SetCreatedAt(t time.Time) *StorageAttachmentUpdate {
	sau.mutation.SetCreatedAt(t)
	return sau
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableCreatedAt(t *time.Time) *StorageAttachmentUpdate {
	if t != nil {
		sau.SetCreatedAt(*t)
	}
	return sau
}

// SetUpdatedAt sets the "updated_at" field.
func (sau *StorageAttachmentUpdate) SetUpdatedAt(t time.Time) *StorageAttachmentUpdate {
	sau.mutation.SetUpdatedAt(t)
	return sau
}

// SetArchivedAt sets the "archived_at" field.
func (sau *StorageAttachmentUpdate) SetArchivedAt(t time.Time) *StorageAttachmentUpdate {
	sau.mutation.SetArchivedAt(t)
	return sau
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (sau *StorageAttachmentUpdate) SetNillableArchivedAt(t *time.Time) *StorageAttachmentUpdate {
	if t != nil {
		sau.SetArchivedAt(*t)
	}
	return sau
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (sau *StorageAttachmentUpdate) ClearArchivedAt() *StorageAttachmentUpdate {
	sau.mutation.ClearArchivedAt()
	return sau
}

// Mutation returns the StorageAttachmentMutation object of the builder.
func (sau *StorageAttachmentUpdate) Mutation() *StorageAttachmentMutation {
	return sau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sau *StorageAttachmentUpdate) Save(ctx context.Context) (int, error) {
	sau.defaults()
	return withHooks(ctx, sau.sqlSave, sau.mutation, sau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sau *StorageAttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := sau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sau *StorageAttachmentUpdate) Exec(ctx context.Context) error {
	_, err := sau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sau *StorageAttachmentUpdate) ExecX(ctx context.Context) {
	if err := sau.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sau *StorageAttachmentUpdate) defaults() {
	if _, ok := sau.mutation.UpdatedAt(); !ok {
		v := storageattachment.UpdateDefaultUpdatedAt()
		sau.mutation.SetUpdatedAt(v)
	}
}

func (sau *StorageAttachmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(storageattachment.Table, storageattachment.Columns, sqlgraph.NewFieldSpec(storageattachment.FieldID, field.TypeString))
	if ps := sau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sau.mutation.AccountID(); ok {
		_spec.SetField(storageattachment.FieldAccountID, field.TypeString, value)
	}
	if value, ok := sau.mutation.OwnerAccountID(); ok {
		_spec.SetField(storageattachment.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := sau.mutation.OwnerUserID(); ok {
		_spec.SetField(storageattachment.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := sau.mutation.UserID(); ok {
		_spec.SetField(storageattachment.FieldUserID, field.TypeString, value)
	}
	if value, ok := sau.mutation.Email(); ok {
		_spec.SetField(storageattachment.FieldEmail, field.TypeString, value)
	}
	if value, ok := sau.mutation.Role(); ok {
		_spec.SetField(storageattachment.FieldRole, field.TypeString, value)
	}
	if value, ok := sau.mutation.Status(); ok {
		_spec.SetField(storageattachment.FieldStatus, field.TypeString, value)
	}
	if value, ok := sau.mutation.Name(); ok {
		_spec.SetField(storageattachment.FieldName, field.TypeString, value)
	}
	if value, ok := sau.mutation.WorkspaceID(); ok {
		_spec.SetField(storageattachment.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := sau.mutation.ResourceID(); ok {
		_spec.SetField(storageattachment.FieldResourceID, field.TypeString, value)
	}
	if value, ok := sau.mutation.ResourceKind(); ok {
		_spec.SetField(storageattachment.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := sau.mutation.OperationID(); ok {
		_spec.SetField(storageattachment.FieldOperationID, field.TypeString, value)
	}
	if value, ok := sau.mutation.Provider(); ok {
		_spec.SetField(storageattachment.FieldProvider, field.TypeString, value)
	}
	if value, ok := sau.mutation.ProviderResourceID(); ok {
		_spec.SetField(storageattachment.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := sau.mutation.URL(); ok {
		_spec.SetField(storageattachment.FieldURL, field.TypeString, value)
	}
	if value, ok := sau.mutation.HoldID(); ok {
		_spec.SetField(storageattachment.FieldHoldID, field.TypeString, value)
	}
	if value, ok := sau.mutation.HoldReleaseID(); ok {
		_spec.SetField(storageattachment.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := sau.mutation.LedgerEntryID(); ok {
		_spec.SetField(storageattachment.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := sau.mutation.WalletTransactionID(); ok {
		_spec.SetField(storageattachment.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := sau.mutation.SettlementID(); ok {
		_spec.SetField(storageattachment.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := sau.mutation.PricingVersion(); ok {
		_spec.SetField(storageattachment.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := sau.mutation.AmountCents(); ok {
		_spec.SetField(storageattachment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AddedAmountCents(); ok {
		_spec.AddField(storageattachment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.BalanceCents(); ok {
		_spec.SetField(storageattachment.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AddedBalanceCents(); ok {
		_spec.AddField(storageattachment.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.FrozenCents(); ok {
		_spec.SetField(storageattachment.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AddedFrozenCents(); ok {
		_spec.AddField(storageattachment.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AvailableCents(); ok {
		_spec.SetField(storageattachment.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AddedAvailableCents(); ok {
		_spec.AddField(storageattachment.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.TotalSpentCents(); ok {
		_spec.SetField(storageattachment.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(storageattachment.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := sau.mutation.Quantity(); ok {
		_spec.SetField(storageattachment.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := sau.mutation.AddedQuantity(); ok {
		_spec.AddField(storageattachment.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := sau.mutation.Unit(); ok {
		_spec.SetField(storageattachment.FieldUnit, field.TypeString, value)
	}
	if value, ok := sau.mutation.Reason(); ok {
		_spec.SetField(storageattachment.FieldReason, field.TypeString, value)
	}
	if value, ok := sau.mutation.Result(); ok {
		_spec.SetField(storageattachment.FieldResult, field.TypeString, value)
	}
	if value, ok := sau.mutation.Source(); ok {
		_spec.SetField(storageattachment.FieldSource, field.TypeString, value)
	}
	if value, ok := sau.mutation.Direction(); ok {
		_spec.SetField(storageattachment.FieldDirection, field.TypeString, value)
	}
	if value, ok := sau.mutation.CreatedAt(); ok {
		_spec.SetField(storageattachment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := sau.mutation.UpdatedAt(); ok {
		_spec.SetField(storageattachment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sau.mutation.ArchivedAt(); ok {
		_spec.SetField(storageattachment.FieldArchivedAt, field.TypeTime, value)
	}
	if sau.mutation.ArchivedAtCleared() {
		_spec.ClearField(storageattachment.FieldArchivedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storageattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	sau.mutation.done = true
	return n, nil
}

// StorageAttachmentUpdateOne is the builder for updating a single StorageAttachment entity.
type StorageAttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StorageAttachmentMutation
}

// SetAccountID sets the "account_id" field.
func (sauo *StorageAttachmentUpdateOne) SetAccountID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetAccountID(s)
	return sauo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableAccountID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetAccountID(*s)
	}
	return sauo
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (sauo *StorageAttachmentUpdateOne) SetOwnerAccountID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetOwnerAccountID(s)
	return sauo
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableOwnerAccountID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetOwnerAccountID(*s)
	}
	return sauo
}

// SetOwnerUserID sets the "owner_user_id" field.
func (sauo *StorageAttachmentUpdateOne) SetOwnerUserID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetOwnerUserID(s)
	return sauo
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableOwnerUserID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetOwnerUserID(*s)
	}
	return sauo
}

// SetUserID sets the "user_id" field.
func (sauo *StorageAttachmentUpdateOne) SetUserID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetUserID(s)
	return sauo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableUserID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetUserID(*s)
	}
	return sauo
}

// SetEmail sets the "email" field.
func (sauo *StorageAttachmentUpdateOne) SetEmail(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetEmail(s)
	return sauo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableEmail(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetEmail(*s)
	}
	return sauo
}

// SetRole sets the "role" field.
func (sauo *StorageAttachmentUpdateOne) SetRole(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetRole(s)
	return sauo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableRole(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetRole(*s)
	}
	return sauo
}

// SetStatus sets the "status" field.
func (sauo *StorageAttachmentUpdateOne) SetStatus(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetStatus(s)
	return sauo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableStatus(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetStatus(*s)
	}
	return sauo
}

// SetName sets the "name" field.
func (sauo *StorageAttachmentUpdateOne) SetName(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetName(s)
	return sauo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableName(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetName(*s)
	}
	return sauo
}

// SetWorkspaceID sets the "workspace_id" field.
func (sauo *StorageAttachmentUpdateOne) SetWorkspaceID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetWorkspaceID(s)
	return sauo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableWorkspaceID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetWorkspaceID(*s)
	}
	return sauo
}

// SetResourceID sets the "resource_id" field.
func (sauo *StorageAttachmentUpdateOne) SetResourceID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetResourceID(s)
	return sauo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableResourceID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetResourceID(*s)
	}
	return sauo
}

// SetResourceKind sets the "resource_kind" field.
func (sauo *StorageAttachmentUpdateOne) SetResourceKind(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetResourceKind(s)
	return sauo
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableResourceKind(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetResourceKind(*s)
	}
	return sauo
}

// SetOperationID sets the "operation_id" field.
func (sauo *StorageAttachmentUpdateOne) SetOperationID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetOperationID(s)
	return sauo
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableOperationID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetOperationID(*s)
	}
	return sauo
}

// SetProvider sets the "provider" field.
func (sauo *StorageAttachmentUpdateOne) SetProvider(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetProvider(s)
	return sauo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableProvider(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetProvider(*s)
	}
	return sauo
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (sauo *StorageAttachmentUpdateOne) SetProviderResourceID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetProviderResourceID(s)
	return sauo
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableProviderResourceID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetProviderResourceID(*s)
	}
	return sauo
}

// SetURL sets the "url" field.
func (sauo *StorageAttachmentUpdateOne) SetURL(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetURL(s)
	return sauo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableURL(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetURL(*s)
	}
	return sauo
}

// SetHoldID sets the "hold_id" field.
func (sauo *StorageAttachmentUpdateOne) SetHoldID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetHoldID(s)
	return sauo
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableHoldID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetHoldID(*s)
	}
	return sauo
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (sauo *StorageAttachmentUpdateOne) SetHoldReleaseID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetHoldReleaseID(s)
	return sauo
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableHoldReleaseID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetHoldReleaseID(*s)
	}
	return sauo
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (sauo *StorageAttachmentUpdateOne) SetLedgerEntryID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetLedgerEntryID(s)
	return sauo
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableLedgerEntryID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetLedgerEntryID(*s)
	}
	return sauo
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (sauo *StorageAttachmentUpdateOne) SetWalletTransactionID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetWalletTransactionID(s)
	return sauo
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableWalletTransactionID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetWalletTransactionID(*s)
	}
	return sauo
}

// SetSettlementID sets the "settlement_id" field.
func (sauo *StorageAttachmentUpdateOne) SetSettlementID(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetSettlementID(s)
	return sauo
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableSettlementID(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetSettlementID(*s)
	}
	return sauo
}

// SetPricingVersion sets the "pricing_version" field.
func (sauo *StorageAttachmentUpdateOne) SetPricingVersion(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetPricingVersion(s)
	return sauo
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillablePricingVersion(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetPricingVersion(*s)
	}
	return sauo
}

// SetAmountCents sets the "amount_cents" field.
func (sauo *StorageAttachmentUpdateOne) SetAmountCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetAmountCents()
	sauo.mutation.SetAmountCents(i)
	return sauo
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableAmountCents(i *int64) *StorageAttachmentUpdateOne {
	if i != nil {
		sauo.SetAmountCents(*i)
	}
	return sauo
}

// AddAmountCents adds i to the "amount_cents" field.
func (sauo *StorageAttachmentUpdateOne) AddAmountCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddAmountCents(i)
	return sauo
}

// SetBalanceCents sets the "balance_cents" field.
func (sauo *StorageAttachmentUpdateOne) SetBalanceCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetBalanceCents()
	sauo.mutation.SetBalanceCents(i)
	return sauo
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableBalanceCents(i *int64) *StorageAttachmentUpdateOne {
	if i != nil {
		sauo.SetBalanceCents(*i)
	}
	return sauo
}

// AddBalanceCents adds i to the "balance_cents" field.
func (sauo *StorageAttachmentUpdateOne) AddBalanceCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddBalanceCents(i)
	return sauo
}

// SetFrozenCents sets the "frozen_cents" field.
func (sauo *StorageAttachmentUpdateOne) SetFrozenCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetFrozenCents()
	sauo.mutation.SetFrozenCents(i)
	return sauo
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableFrozenCents(i *int64) *StorageAttachmentUpdateOne {
	if i != nil {
		sauo.SetFrozenCents(*i)
	}
	return sauo
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (sauo *StorageAttachmentUpdateOne) AddFrozenCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddFrozenCents(i)
	return sauo
}

// SetAvailableCents sets the "available_cents" field.
func (sauo *StorageAttachmentUpdateOne) SetAvailableCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetAvailableCents()
	sauo.mutation.SetAvailableCents(i)
	return sauo
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableAvailableCents(i *int64) *StorageAttachmentUpdateOne {
	if i != nil {
		sauo.SetAvailableCents(*i)
	}
	return sauo
}

// AddAvailableCents adds i to the "available_cents" field.
func (sauo *StorageAttachmentUpdateOne) AddAvailableCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddAvailableCents(i)
	return sauo
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (sauo *StorageAttachmentUpdateOne) SetTotalSpentCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetTotalSpentCents()
	sauo.mutation.SetTotalSpentCents(i)
	return sauo
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableTotalSpentCents(i *int64) *StorageAttachmentUpdateOne {
	if i != nil {
		sauo.SetTotalSpentCents(*i)
	}
	return sauo
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (sauo *StorageAttachmentUpdateOne) AddTotalSpentCents(i int64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddTotalSpentCents(i)
	return sauo
}

// SetQuantity sets the "quantity" field.
func (sauo *StorageAttachmentUpdateOne) SetQuantity(f float64) *StorageAttachmentUpdateOne {
	sauo.mutation.ResetQuantity()
	sauo.mutation.SetQuantity(f)
	return sauo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableQuantity(f *float64) *StorageAttachmentUpdateOne {
	if f != nil {
		sauo.SetQuantity(*f)
	}
	return sauo
}

// AddQuantity adds f to the "quantity" field.
func (sauo *StorageAttachmentUpdateOne) AddQuantity(f float64) *StorageAttachmentUpdateOne {
	sauo.mutation.AddQuantity(f)
	return sauo
}

// SetUnit sets the "unit" field.
func (sauo *StorageAttachmentUpdateOne) SetUnit(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetUnit(s)
	return sauo
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableUnit(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetUnit(*s)
	}
	return sauo
}

// SetReason sets the "reason" field.
func (sauo *StorageAttachmentUpdateOne) SetReason(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetReason(s)
	return sauo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableReason(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetReason(*s)
	}
	return sauo
}

// SetResult sets the "result" field.
func (sauo *StorageAttachmentUpdateOne) SetResult(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetResult(s)
	return sauo
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableResult(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetResult(*s)
	}
	return sauo
}

// SetSource sets the "source" field.
func (sauo *StorageAttachmentUpdateOne) SetSource(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetSource(s)
	return sauo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableSource(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetSource(*s)
	}
	return sauo
}

// SetDirection sets the "direction" field.
func (sauo *StorageAttachmentUpdateOne) SetDirection(s string) *StorageAttachmentUpdateOne {
	sauo.mutation.SetDirection(s)
	return sauo
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableDirection(s *string) *StorageAttachmentUpdateOne {
	if s != nil {
		sauo.SetDirection(*s)
	}
	return sauo
}

// SetCreatedAt sets the "created_at" field.
func (sauo *StorageAttachmentUpdateOne) SetCreatedAt(t time.Time) *StorageAttachmentUpdateOne {
	sauo.mutation.SetCreatedAt(t)
	return sauo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableCreatedAt(t *time.Time) *StorageAttachmentUpdateOne {
	if t != nil {
		sauo.SetCreatedAt(*t)
	}
	return sauo
}

// SetUpdatedAt sets the "updated_at" field.
func (sauo *StorageAttachmentUpdateOne) SetUpdatedAt(t time.Time) *StorageAttachmentUpdateOne {
	sauo.mutation.SetUpdatedAt(t)
	return sauo
}

// SetArchivedAt sets the "archived_at" field.
func (sauo *StorageAttachmentUpdateOne) SetArchivedAt(t time.Time) *StorageAttachmentUpdateOne {
	sauo.mutation.SetArchivedAt(t)
	return sauo
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (sauo *StorageAttachmentUpdateOne) SetNillableArchivedAt(t *time.Time) *StorageAttachmentUpdateOne {
	if t != nil {
		sauo.SetArchivedAt(*t)
	}
	return sauo
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (sauo *StorageAttachmentUpdateOne) ClearArchivedAt() *StorageAttachmentUpdateOne {
	sauo.mutation.ClearArchivedAt()
	return sauo
}

// Mutation returns the StorageAttachmentMutation object of the builder.
func (sauo *StorageAttachmentUpdateOne) Mutation() *StorageAttachmentMutation {
	return sauo.mutation
}

// Where appends a list predicates to the StorageAttachmentUpdate builder.
func (sauo *StorageAttachmentUpdateOne) Where(ps ...predicate.StorageAttachment) *StorageAttachmentUpdateOne {
	sauo.mutation.Where(ps...)
	return sauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sauo *StorageAttachmentUpdateOne) Select(field string, fields ...string) *StorageAttachmentUpdateOne {
	sauo.fields = append([]string{field}, fields...)
	return sauo
}

// Save executes the query and returns the updated StorageAttachment entity.
func (sauo *StorageAttachmentUpdateOne) Save(ctx context.Context) (*StorageAttachment, error) {
	sauo.defaults()
	return withHooks(ctx, sauo.sqlSave, sauo.mutation, sauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (sauo *StorageAttachmentUpdateOne) SaveX(ctx context.Context) *StorageAttachment {
	node, err := sauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sauo *StorageAttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := sauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sauo *StorageAttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := sauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sauo *StorageAttachmentUpdateOne) defaults() {
	if _, ok := sauo.mutation.UpdatedAt(); !ok {
		v := storageattachment.UpdateDefaultUpdatedAt()
		sauo.mutation.SetUpdatedAt(v)
	}
}

func (sauo *StorageAttachmentUpdateOne) sqlSave(ctx context.Context) (_node *StorageAttachment, err error) {
	_spec := sqlgraph.NewUpdateSpec(storageattachment.Table, storageattachment.Columns, sqlgraph.NewFieldSpec(storageattachment.FieldID, field.TypeString))
	id, ok := sauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StorageAttachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storageattachment.FieldID)
		for _, f := range fields {
			if !storageattachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storageattachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sauo.mutation.AccountID(); ok {
		_spec.SetField(storageattachment.FieldAccountID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.OwnerAccountID(); ok {
		_spec.SetField(storageattachment.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.OwnerUserID(); ok {
		_spec.SetField(storageattachment.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.UserID(); ok {
		_spec.SetField(storageattachment.FieldUserID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Email(); ok {
		_spec.SetField(storageattachment.FieldEmail, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Role(); ok {
		_spec.SetField(storageattachment.FieldRole, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Status(); ok {
		_spec.SetField(storageattachment.FieldStatus, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Name(); ok {
		_spec.SetField(storageattachment.FieldName, field.TypeString, value)
	}
	if value, ok := sauo.mutation.WorkspaceID(); ok {
		_spec.SetField(storageattachment.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.ResourceID(); ok {
		_spec.SetField(storageattachment.FieldResourceID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.ResourceKind(); ok {
		_spec.SetField(storageattachment.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := sauo.mutation.OperationID(); ok {
		_spec.SetField(storageattachment.FieldOperationID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Provider(); ok {
		_spec.SetField(storageattachment.FieldProvider, field.TypeString, value)
	}
	if value, ok := sauo.mutation.ProviderResourceID(); ok {
		_spec.SetField(storageattachment.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.URL(); ok {
		_spec.SetField(storageattachment.FieldURL, field.TypeString, value)
	}
	if value, ok := sauo.mutation.HoldID(); ok {
		_spec.SetField(storageattachment.FieldHoldID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.HoldReleaseID(); ok {
		_spec.SetField(storageattachment.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.LedgerEntryID(); ok {
		_spec.SetField(storageattachment.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.WalletTransactionID(); ok {
		_spec.SetField(storageattachment.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.SettlementID(); ok {
		_spec.SetField(storageattachment.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := sauo.mutation.PricingVersion(); ok {
		_spec.SetField(storageattachment.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := sauo.mutation.AmountCents(); ok {
		_spec.SetField(storageattachment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AddedAmountCents(); ok {
		_spec.AddField(storageattachment.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.BalanceCents(); ok {
		_spec.SetField(storageattachment.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AddedBalanceCents(); ok {
		_spec.AddField(storageattachment.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.FrozenCents(); ok {
		_spec.SetField(storageattachment.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AddedFrozenCents(); ok {
		_spec.AddField(storageattachment.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AvailableCents(); ok {
		_spec.SetField(storageattachment.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AddedAvailableCents(); ok {
		_spec.AddField(storageattachment.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.TotalSpentCents(); ok {
		_spec.SetField(storageattachment.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(storageattachment.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := sauo.mutation.Quantity(); ok {
		_spec.SetField(storageattachment.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := sauo.mutation.AddedQuantity(); ok {
		_spec.AddField(storageattachment.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := sauo.mutation.Unit(); ok {
		_spec.SetField(storageattachment.FieldUnit, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Reason(); ok {
		_spec.SetField(storageattachment.FieldReason, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Result(); ok {
		_spec.SetField(storageattachment.FieldResult, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Source(); ok {
		_spec.SetField(storageattachment.FieldSource, field.TypeString, value)
	}
	if value, ok := sauo.mutation.Direction(); ok {
		_spec.SetField(storageattachment.FieldDirection, field.TypeString, value)
	}
	if value, ok := sauo.mutation.CreatedAt(); ok {
		_spec.SetField(storageattachment.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := sauo.mutation.UpdatedAt(); ok {
		_spec.SetField(storageattachment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := sauo.mutation.ArchivedAt(); ok {
		_spec.SetField(storageattachment.FieldArchivedAt, field.TypeTime, value)
	}
	if sauo.mutation.ArchivedAtCleared() {
		_spec.ClearField(storageattachment.FieldArchivedAt, field.TypeTime)
	}
	_node = &StorageAttachment{config: sauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storageattachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	sauo.mutation.done = true
	return _node, nil
}
