// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/supportticketmapping"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupportTicketMappingDelete is the builder for deleting a SupportTicketMapping entity.
type SupportTicketMappingDelete struct {
	config
	hooks    []Hook
	mutation *SupportTicketMappingMutation
}

// Where appends a list predicates to the SupportTicketMappingDelete builder.
func (stmd *SupportTicketMappingDelete) Where(ps ...predicate.SupportTicketMapping) *SupportTicketMappingDelete {
	stmd.mutation.Where(ps...)
	return stmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (stmd *SupportTicketMappingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, stmd.sqlExec, stmd.mutation, stmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (stmd *SupportTicketMappingDelete) ExecX(ctx context.Context) int {
	n, err := stmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (stmd *SupportTicketMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(supportticketmapping.Table, sqlgraph.NewFieldSpec(supportticketmapping.FieldID, field.TypeString))
	if ps := stmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, stmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	stmd.mutation.done = true
	return affected, err
}

// SupportTicketMappingDeleteOne is the builder for deleting a single SupportTicketMapping entity.
type SupportTicketMappingDeleteOne struct {
	stmd *SupportTicketMappingDelete
}

// Where appends a list predicates to the SupportTicketMappingDelete builder.
func (stmdo *SupportTicketMappingDeleteOne) Where(ps ...predicate.SupportTicketMapping) *SupportTicketMappingDeleteOne {
	stmdo.stmd.mutation.Where(ps...)
	return stmdo
}

// Exec executes the deletion query.
func (stmdo *SupportTicketMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := stmdo.stmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{supportticketmapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stmdo *SupportTicketMappingDeleteOne) ExecX(ctx context.Context) {
	if err := stmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
