// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/walletprojection"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WalletProjectionCreate is the builder for creating a WalletProjection entity.
type WalletProjectionCreate struct {
	config
	mutation *WalletProjectionMutation
	hooks    []Hook
}

// SetAccountID sets the "account_id" field.
func (wpc *WalletProjectionCreate) SetAccountID(s string) *WalletProjectionCreate {
	wpc.mutation.SetAccountID(s)
	return wpc
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableAccountID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetAccountID(*s)
	}
	return wpc
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (wpc *WalletProjectionCreate) SetOwnerAccountID(s string) *WalletProjectionCreate {
	wpc.mutation.SetOwnerAccountID(s)
	return wpc
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableOwnerAccountID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetOwnerAccountID(*s)
	}
	return wpc
}

// SetOwnerUserID sets the "owner_user_id" field.
func (wpc *WalletProjectionCreate) SetOwnerUserID(s string) *WalletProjectionCreate {
	wpc.mutation.SetOwnerUserID(s)
	return wpc
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableOwnerUserID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetOwnerUserID(*s)
	}
	return wpc
}

// SetUserID sets the "user_id" field.
func (wpc *WalletProjectionCreate) SetUserID(s string) *WalletProjectionCreate {
	wpc.mutation.SetUserID(s)
	return wpc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableUserID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetUserID(*s)
	}
	return wpc
}

// SetEmail sets the "email" field.
func (wpc *WalletProjectionCreate) SetEmail(s string) *WalletProjectionCreate {
	wpc.mutation.SetEmail(s)
	return wpc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableEmail(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetEmail(*s)
	}
	return wpc
}

// SetRole sets the "role" field.
func (wpc *WalletProjectionCreate) SetRole(s string) *WalletProjectionCreate {
	wpc.mutation.SetRole(s)
	return wpc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableRole(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetRole(*s)
	}
	return wpc
}

// SetStatus sets the "status" field.
func (wpc *WalletProjectionCreate) SetStatus(s string) *WalletProjectionCreate {
	wpc.mutation.SetStatus(s)
	return wpc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableStatus(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetStatus(*s)
	}
	return wpc
}

// SetName sets the "name" field.
func (wpc *WalletProjectionCreate) SetName(s string) *WalletProjectionCreate {
	wpc.mutation.SetName(s)
	return wpc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableName(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetName(*s)
	}
	return wpc
}

// SetWorkspaceID sets the "workspace_id" field.
func (wpc *WalletProjectionCreate) SetWorkspaceID(s string) *WalletProjectionCreate {
	wpc.mutation.SetWorkspaceID(s)
	return wpc
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableWorkspaceID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetWorkspaceID(*s)
	}
	return wpc
}

// SetResourceID sets the "resource_id" field.
func (wpc *WalletProjectionCreate) SetResourceID(s string) *WalletProjectionCreate {
	wpc.mutation.SetResourceID(s)
	return wpc
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableResourceID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetResourceID(*s)
	}
	return wpc
}

// SetResourceKind sets the "resource_kind" field.
func (wpc *WalletProjectionCreate) SetResourceKind(s string) *WalletProjectionCreate {
	wpc.mutation.SetResourceKind(s)
	return wpc
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableResourceKind(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetResourceKind(*s)
	}
	return wpc
}

// SetOperationID sets the "operation_id" field.
func (wpc *WalletProjectionCreate) SetOperationID(s string) *WalletProjectionCreate {
	wpc.mutation.SetOperationID(s)
	return wpc
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableOperationID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetOperationID(*s)
	}
	return wpc
}

// SetProvider sets the "provider" field.
func (wpc *WalletProjectionCreate) SetProvider(s string) *WalletProjectionCreate {
	wpc.mutation.SetProvider(s)
	return wpc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableProvider(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetProvider(*s)
	}
	return wpc
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (wpc *WalletProjectionCreate) SetProviderResourceID(s string) *WalletProjectionCreate {
	wpc.mutation.SetProviderResourceID(s)
	return wpc
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableProviderResourceID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetProviderResourceID(*s)
	}
	return wpc
}

// SetURL sets the "url" field.
func (wpc *WalletProjectionCreate) SetURL(s string) *WalletProjectionCreate {
	wpc.mutation.SetURL(s)
	return wpc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableURL(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetURL(*s)
	}
	return wpc
}

// SetHoldID sets the "hold_id" field.
func (wpc *WalletProjectionCreate) SetHoldID(s string) *WalletProjectionCreate {
	wpc.mutation.SetHoldID(s)
	return wpc
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableHoldID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetHoldID(*s)
	}
	return wpc
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (wpc *WalletProjectionCreate) SetHoldReleaseID(s string) *WalletProjectionCreate {
	wpc.mutation.SetHoldReleaseID(s)
	return wpc
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableHoldReleaseID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetHoldReleaseID(*s)
	}
	return wpc
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (wpc *WalletProjectionCreate) SetLedgerEntryID(s string) *WalletProjectionCreate {
	wpc.mutation.SetLedgerEntryID(s)
	return wpc
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableLedgerEntryID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetLedgerEntryID(*s)
	}
	return wpc
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (wpc *WalletProjectionCreate) SetWalletTransactionID(s string) *WalletProjectionCreate {
	wpc.mutation.SetWalletTransactionID(s)
	return wpc
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableWalletTransactionID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetWalletTransactionID(*s)
	}
	return wpc
}

// SetSettlementID sets the "settlement_id" field.
func (wpc *WalletProjectionCreate) SetSettlementID(s string) *WalletProjectionCreate {
	wpc.mutation.SetSettlementID(s)
	return wpc
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableSettlementID(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetSettlementID(*s)
	}
	return wpc
}

// SetPricingVersion sets the "pricing_version" field.
func (wpc *WalletProjectionCreate) SetPricingVersion(s string) *WalletProjectionCreate {
	wpc.mutation.SetPricingVersion(s)
	return wpc
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillablePricingVersion(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetPricingVersion(*s)
	}
	return wpc
}

// SetAmountCents sets the "amount_cents" field.
func (wpc *WalletProjectionCreate) SetAmountCents(i int64) *WalletProjectionCreate {
	wpc.mutation.SetAmountCents(i)
	return wpc
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableAmountCents(i *int64) *WalletProjectionCreate {
	if i != nil {
		wpc.SetAmountCents(*i)
	}
	return wpc
}

// SetBalanceCents sets the "balance_cents" field.
func (wpc *WalletProjectionCreate) SetBalanceCents(i int64) *WalletProjectionCreate {
	wpc.mutation.SetBalanceCents(i)
	return wpc
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableBalanceCents(i *int64) *WalletProjectionCreate {
	if i != nil {
		wpc.SetBalanceCents(*i)
	}
	return wpc
}

// SetFrozenCents sets the "frozen_cents" field.
func (wpc *WalletProjectionCreate) SetFrozenCents(i int64) *WalletProjectionCreate {
	wpc.mutation.SetFrozenCents(i)
	return wpc
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableFrozenCents(i *int64) *WalletProjectionCreate {
	if i != nil {
		wpc.SetFrozenCents(*i)
	}
	return wpc
}

// SetAvailableCents sets the "available_cents" field.
func (wpc *WalletProjectionCreate) SetAvailableCents(i int64) *WalletProjectionCreate {
	wpc.mutation.SetAvailableCents(i)
	return wpc
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableAvailableCents(i *int64) *WalletProjectionCreate {
	if i != nil {
		wpc.SetAvailableCents(*i)
	}
	return wpc
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (wpc *WalletProjectionCreate) SetTotalSpentCents(i int64) *WalletProjectionCreate {
	wpc.mutation.SetTotalSpentCents(i)
	return wpc
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableTotalSpentCents(i *int64) *WalletProjectionCreate {
	if i != nil {
		wpc.SetTotalSpentCents(*i)
	}
	return wpc
}

// SetQuantity sets the "quantity" field.
func (wpc *WalletProjectionCreate) SetQuantity(f float64) *WalletProjectionCreate {
	wpc.mutation.SetQuantity(f)
	return wpc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableQuantity(f *float64) *WalletProjectionCreate {
	if f != nil {
		wpc.SetQuantity(*f)
	}
	return wpc
}

// SetUnit sets the "unit" field.
func (wpc *WalletProjectionCreate) SetUnit(s string) *WalletProjectionCreate {
	wpc.mutation.SetUnit(s)
	return wpc
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableUnit(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetUnit(*s)
	}
	return wpc
}

// SetReason sets the "reason" field.
func (wpc *WalletProjectionCreate) SetReason(s string) *WalletProjectionCreate {
	wpc.mutation.SetReason(s)
	return wpc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableReason(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetReason(*s)
	}
	return wpc
}

// SetResult sets the "result" field.
func (wpc *WalletProjectionCreate) SetResult(s string) *WalletProjectionCreate {
	wpc.mutation.SetResult(s)
	return wpc
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableResult(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetResult(*s)
	}
	return wpc
}

// SetSource sets the "source" field.
func (wpc *WalletProjectionCreate) SetSource(s string) *WalletProjectionCreate {
	wpc.mutation.SetSource(s)
	return wpc
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableSource(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetSource(*s)
	}
	return wpc
}

// SetDirection sets the "direction" field.
func (wpc *WalletProjectionCreate) SetDirection(s string) *WalletProjectionCreate {
	wpc.mutation.SetDirection(s)
	return wpc
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableDirection(s *string) *WalletProjectionCreate {
	if s != nil {
		wpc.SetDirection(*s)
	}
	return wpc
}

// SetCreatedAt sets the "created_at" field.
func (wpc *WalletProjectionCreate) SetCreatedAt(t time.Time) *WalletProjectionCreate {
	wpc.mutation.SetCreatedAt(t)
	return wpc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableCreatedAt(t *time.Time) *WalletProjectionCreate {
	if t != nil {
		wpc.SetCreatedAt(*t)
	}
	return wpc
}

// SetUpdatedAt sets the "updated_at" field.
func (wpc *WalletProjectionCreate) SetUpdatedAt(t time.Time) *WalletProjectionCreate {
	wpc.mutation.SetUpdatedAt(t)
	return wpc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableUpdatedAt(t *time.Time) *WalletProjectionCreate {
	if t != nil {
		wpc.SetUpdatedAt(*t)
	}
	return wpc
}

// SetArchivedAt sets the "archived_at" field.
func (wpc *WalletProjectionCreate) SetArchivedAt(t time.Time) *WalletProjectionCreate {
	wpc.mutation.SetArchivedAt(t)
	return wpc
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (wpc *WalletProjectionCreate) SetNillableArchivedAt(t *time.Time) *WalletProjectionCreate {
	if t != nil {
		wpc.SetArchivedAt(*t)
	}
	return wpc
}

// SetID sets the "id" field.
func (wpc *WalletProjectionCreate) SetID(s string) *WalletProjectionCreate {
	wpc.mutation.SetID(s)
	return wpc
}

// Mutation returns the WalletProjectionMutation object of the builder.
func (wpc *WalletProjectionCreate) Mutation() *WalletProjectionMutation {
	return wpc.mutation
}

// Save creates the WalletProjection in the database.
func (wpc *WalletProjectionCreate) Save(ctx context.Context) (*WalletProjection, error) {
	wpc.defaults()
	return withHooks(ctx, wpc.sqlSave, wpc.mutation, wpc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wpc *WalletProjectionCreate) SaveX(ctx context.Context) *WalletProjection {
	v, err := wpc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wpc *WalletProjectionCreate) Exec(ctx context.Context) error {
	_, err := wpc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wpc *WalletProjectionCreate) ExecX(ctx context.Context) {
	if err := wpc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wpc *WalletProjectionCreate) defaults() {
	if _, ok := wpc.mutation.AccountID(); !ok {
		v := walletprojection.DefaultAccountID
		wpc.mutation.SetAccountID(v)
	}
	if _, ok := wpc.mutation.OwnerAccountID(); !ok {
		v := walletprojection.DefaultOwnerAccountID
		wpc.mutation.SetOwnerAccountID(v)
	}
	if _, ok := wpc.mutation.OwnerUserID(); !ok {
		v := walletprojection.DefaultOwnerUserID
		wpc.mutation.SetOwnerUserID(v)
	}
	if _, ok := wpc.mutation.UserID(); !ok {
		v := walletprojection.DefaultUserID
		wpc.mutation.SetUserID(v)
	}
	if _, ok := wpc.mutation.Email(); !ok {
		v := walletprojection.DefaultEmail
		wpc.mutation.SetEmail(v)
	}
	if _, ok := wpc.mutation.Role(); !ok {
		v := walletprojection.DefaultRole
		wpc.mutation.SetRole(v)
	}
	if _, ok := wpc.mutation.Status(); !ok {
		v := walletprojection.DefaultStatus
		wpc.mutation.SetStatus(v)
	}
	if _, ok := wpc.mutation.Name(); !ok {
		v := walletprojection.DefaultName
		wpc.mutation.SetName(v)
	}
	if _, ok := wpc.mutation.WorkspaceID(); !ok {
		v := walletprojection.DefaultWorkspaceID
		wpc.mutation.SetWorkspaceID(v)
	}
	if _, ok := wpc.mutation.ResourceID(); !ok {
		v := walletprojection.DefaultResourceID
		wpc.mutation.SetResourceID(v)
	}
	if _, ok := wpc.mutation.ResourceKind(); !ok {
		v := walletprojection.DefaultResourceKind
		wpc.mutation.SetResourceKind(v)
	}
	if _, ok := wpc.mutation.OperationID(); !ok {
		v := walletprojection.DefaultOperationID
		wpc.mutation.SetOperationID(v)
	}
	if _, ok := wpc.mutation.Provider(); !ok {
		v := walletprojection.DefaultProvider
		wpc.mutation.SetProvider(v)
	}
	if _, ok := wpc.mutation.ProviderResourceID(); !ok {
		v := walletprojection.DefaultProviderResourceID
		wpc.mutation.SetProviderResourceID(v)
	}
	if _, ok := wpc.mutation.URL(); !ok {
		v := walletprojection.DefaultURL
		wpc.mutation.SetURL(v)
	}
	if _, ok := wpc.mutation.HoldID(); !ok {
		v := walletprojection.DefaultHoldID
		wpc.mutation.SetHoldID(v)
	}
	if _, ok := wpc.mutation.HoldReleaseID(); !ok {
		v := walletprojection.DefaultHoldReleaseID
		wpc.mutation.SetHoldReleaseID(v)
	}
	if _, ok := wpc.mutation.LedgerEntryID(); !ok {
		v := walletprojection.DefaultLedgerEntryID
		wpc.mutation.SetLedgerEntryID(v)
	}
	if _, ok := wpc.mutation.WalletTransactionID(); !ok {
		v := walletprojection.DefaultWalletTransactionID
		wpc.mutation.SetWalletTransactionID(v)
	}
	if _, ok := wpc.mutation.SettlementID(); !ok {
		v := walletprojection.DefaultSettlementID
		wpc.mutation.SetSettlementID(v)
	}
	if _, ok := wpc.mutation.PricingVersion(); !ok {
		v := walletprojection.DefaultPricingVersion
		wpc.mutation.SetPricingVersion(v)
	}
	if _, ok := wpc.mutation.AmountCents(); !ok {
		v := walletprojection.DefaultAmountCents
		wpc.mutation.SetAmountCents(v)
	}
	if _, ok := wpc.mutation.BalanceCents(); !ok {
		v := walletprojection.DefaultBalanceCents
		wpc.mutation.SetBalanceCents(v)
	}
	if _, ok := wpc.mutation.FrozenCents(); !ok {
		v := walletprojection.DefaultFrozenCents
		wpc.mutation.SetFrozenCents(v)
	}
	if _, ok := wpc.mutation.AvailableCents(); !ok {
		v := walletprojection.DefaultAvailableCents
		wpc.mutation.SetAvailableCents(v)
	}
	if _, ok := wpc.mutation.TotalSpentCents(); !ok {
		v := walletprojection.DefaultTotalSpentCents
		wpc.mutation.SetTotalSpentCents(v)
	}
	if _, ok := wpc.mutation.Quantity(); !ok {
		v := walletprojection.DefaultQuantity
		wpc.mutation.SetQuantity(v)
	}
	if _, ok := wpc.mutation.Unit(); !ok {
		v := walletprojection.DefaultUnit
		wpc.mutation.SetUnit(v)
	}
	if _, ok := wpc.mutation.Reason(); !ok {
		v := walletprojection.DefaultReason
		wpc.mutation.SetReason(v)
	}
	if _, ok := wpc.mutation.Result(); !ok {
		v := walletprojection.DefaultResult
		wpc.mutation.SetResult(v)
	}
	if _, ok := wpc.mutation.Source(); !ok {
		v := walletprojection.DefaultSource
		wpc.mutation.SetSource(v)
	}
	if _, ok := wpc.mutation.Direction(); !ok {
		v := walletprojection.DefaultDirection
		wpc.mutation.SetDirection(v)
	}
	if _, ok := wpc.mutation.CreatedAt(); !ok {
		v := walletprojection.DefaultCreatedAt()
		wpc.mutation.SetCreatedAt(v)
	}
	if _, ok := wpc.mutation.UpdatedAt(); !ok {
		v := walletprojection.DefaultUpdatedAt()
		wpc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wpc *WalletProjectionCreate) check() error {
	if _, ok := wpc.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "WalletProjection.account_id"`)}
	}
	if _, ok := wpc.mutation.OwnerAccountID(); !ok {
		return &ValidationError{Name: "owner_account_id", err: errors.New(`ent: missing required field "WalletProjection.owner_account_id"`)}
	}
	if _, ok := wpc.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "WalletProjection.owner_user_id"`)}
	}
	if _, ok := wpc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "WalletProjection.user_id"`)}
	}
	if _, ok := wpc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "WalletProjection.email"`)}
	}
	if _, ok := wpc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "WalletProjection.role"`)}
	}
	if _, ok := wpc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "WalletProjection.status"`)}
	}
	if _, ok := wpc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "WalletProjection.name"`)}
	}
	if _, ok := wpc.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "WalletProjection.workspace_id"`)}
	}
	if _, ok := wpc.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "WalletProjection.resource_id"`)}
	}
	if _, ok := wpc.mutation.ResourceKind(); !ok {
		return &ValidationError{Name: "resource_kind", err: errors.New(`ent: missing required field "WalletProjection.resource_kind"`)}
	}
	if _, ok := wpc.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "WalletProjection.operation_id"`)}
	}
	if _, ok := wpc.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "WalletProjection.provider"`)}
	}
	if _, ok := wpc.mutation.ProviderResourceID(); !ok {
		return &ValidationError{Name: "provider_resource_id", err: errors.New(`ent: missing required field "WalletProjection.provider_resource_id"`)}
	}
	if _, ok := wpc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "WalletProjection.url"`)}
	}
	if _, ok := wpc.mutation.HoldID(); !ok {
		return &ValidationError{Name: "hold_id", err: errors.New(`ent: missing required field "WalletProjection.hold_id"`)}
	}
	if _, ok := wpc.mutation.HoldReleaseID(); !ok {
		return &ValidationError{Name: "hold_release_id", err: errors.New(`ent: missing required field "WalletProjection.hold_release_id"`)}
	}
	if _, ok := wpc.mutation.LedgerEntryID(); !ok {
		return &ValidationError{Name: "ledger_entry_id", err: errors.New(`ent: missing required field "WalletProjection.ledger_entry_id"`)}
	}
	if _, ok := wpc.mutation.WalletTransactionID(); !ok {
		return &ValidationError{Name: "wallet_transaction_id", err: errors.New(`ent: missing required field "WalletProjection.wallet_transaction_id"`)}
	}
	if _, ok := wpc.mutation.SettlementID(); !ok {
		return &ValidationError{Name: "settlement_id", err: errors.New(`ent: missing required field "WalletProjection.settlement_id"`)}
	}
	if _, ok := wpc.mutation.PricingVersion(); !ok {
		return &ValidationError{Name: "pricing_version", err: errors.New(`ent: missing required field "WalletProjection.pricing_version"`)}
	}
	if _, ok := wpc.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "WalletProjection.amount_cents"`)}
	}
	if _, ok := wpc.mutation.BalanceCents(); !ok {
		return &ValidationError{Name: "balance_cents", err: errors.New(`ent: missing required field "WalletProjection.balance_cents"`)}
	}
	if _, ok := wpc.mutation.FrozenCents(); !ok {
		return &ValidationError{Name: "frozen_cents", err: errors.New(`ent: missing required field "WalletProjection.frozen_cents"`)}
	}
	if _, ok := wpc.mutation.AvailableCents(); !ok {
		return &ValidationError{Name: "available_cents", err: errors.New(`ent: missing required field "WalletProjection.available_cents"`)}
	}
	if _, ok := wpc.mutation.TotalSpentCents(); !ok {
		return &ValidationError{Name: "total_spent_cents", err: errors.New(`ent: missing required field "WalletProjection.total_spent_cents"`)}
	}
	if _, ok := wpc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "WalletProjection.quantity"`)}
	}
	if _, ok := wpc.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "WalletProjection.unit"`)}
	}
	if _, ok := wpc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "WalletProjection.reason"`)}
	}
	if _, ok := wpc.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "WalletProjection.result"`)}
	}
	if _, ok := wpc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "WalletProjection.source"`)}
	}
	if _, ok := wpc.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "WalletProjection.direction"`)}
	}
	if _, ok := wpc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WalletProjection.created_at"`)}
	}
	if _, ok := wpc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WalletProjection.updated_at"`)}
	}
	if v, ok := wpc.mutation.ID(); ok {
		if err := walletprojection.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "WalletProjection.id": %w`, err)}
		}
	}
	return nil
}

func (wpc *WalletProjectionCreate) sqlSave(ctx context.Context) (*WalletProjection, error) {
	if err := wpc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wpc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wpc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WalletProjection.ID type: %T", _spec.ID.Value)
		}
	}
	wpc.mutation.id = &_node.ID
	wpc.mutation.done = true
	return _node, nil
}

func (wpc *WalletProjectionCreate) createSpec() (*WalletProjection, *sqlgraph.CreateSpec) {
	var (
		_node = &WalletProjection{config: wpc.config}
		_spec = sqlgraph.NewCreateSpec(walletprojection.Table, sqlgraph.NewFieldSpec(walletprojection.FieldID, field.TypeString))
	)
	if id, ok := wpc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := wpc.mutation.AccountID(); ok {
		_spec.SetField(walletprojection.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := wpc.mutation.OwnerAccountID(); ok {
		_spec.SetField(walletprojection.FieldOwnerAccountID, field.TypeString, value)
		_node.OwnerAccountID = value
	}
	if value, ok := wpc.mutation.OwnerUserID(); ok {
		_spec.SetField(walletprojection.FieldOwnerUserID, field.TypeString, value)
		_node.OwnerUserID = value
	}
	if value, ok := wpc.mutation.UserID(); ok {
		_spec.SetField(walletprojection.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := wpc.mutation.Email(); ok {
		_spec.SetField(walletprojection.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := wpc.mutation.Role(); ok {
		_spec.SetField(walletprojection.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := wpc.mutation.Status(); ok {
		_spec.SetField(walletprojection.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := wpc.mutation.Name(); ok {
		_spec.SetField(walletprojection.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wpc.mutation.WorkspaceID(); ok {
		_spec.SetField(walletprojection.FieldWorkspaceID, field.TypeString, value)
		_node.WorkspaceID = value
	}
	if value, ok := wpc.mutation.ResourceID(); ok {
		_spec.SetField(walletprojection.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := wpc.mutation.ResourceKind(); ok {
		_spec.SetField(walletprojection.FieldResourceKind, field.TypeString, value)
		_node.ResourceKind = value
	}
	if value, ok := wpc.mutation.OperationID(); ok {
		_spec.SetField(walletprojection.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := wpc.mutation.Provider(); ok {
		_spec.SetField(walletprojection.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := wpc.mutation.ProviderResourceID(); ok {
		_spec.SetField(walletprojection.FieldProviderResourceID, field.TypeString, value)
		_node.ProviderResourceID = value
	}
	if value, ok := wpc.mutation.URL(); ok {
		_spec.SetField(walletprojection.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := wpc.mutation.HoldID(); ok {
		_spec.SetField(walletprojection.FieldHoldID, field.TypeString, value)
		_node.HoldID = value
	}
	if value, ok := wpc.mutation.HoldReleaseID(); ok {
		_spec.SetField(walletprojection.FieldHoldReleaseID, field.TypeString, value)
		_node.HoldReleaseID = value
	}
	if value, ok := wpc.mutation.LedgerEntryID(); ok {
		_spec.SetField(walletprojection.FieldLedgerEntryID, field.TypeString, value)
		_node.LedgerEntryID = value
	}
	if value, ok := wpc.mutation.WalletTransactionID(); ok {
		_spec.SetField(walletprojection.FieldWalletTransactionID, field.TypeString, value)
		_node.WalletTransactionID = value
	}
	if value, ok := wpc.mutation.SettlementID(); ok {
		_spec.SetField(walletprojection.FieldSettlementID, field.TypeString, value)
		_node.SettlementID = value
	}
	if value, ok := wpc.mutation.PricingVersion(); ok {
		_spec.SetField(walletprojection.FieldPricingVersion, field.TypeString, value)
		_node.PricingVersion = value
	}
	if value, ok := wpc.mutation.AmountCents(); ok {
		_spec.SetField(walletprojection.FieldAmountCents, field.TypeInt64, value)
		_node.AmountCents = value
	}
	if value, ok := wpc.mutation.BalanceCents(); ok {
		_spec.SetField(walletprojection.FieldBalanceCents, field.TypeInt64, value)
		_node.BalanceCents = value
	}
	if value, ok := wpc.mutation.FrozenCents(); ok {
		_spec.SetField(walletprojection.FieldFrozenCents, field.TypeInt64, value)
		_node.FrozenCents = value
	}
	if value, ok := wpc.mutation.AvailableCents(); ok {
		_spec.SetField(walletprojection.FieldAvailableCents, field.TypeInt64, value)
		_node.AvailableCents = value
	}
	if value, ok := wpc.mutation.TotalSpentCents(); ok {
		_spec.SetField(walletprojection.FieldTotalSpentCents, field.TypeInt64, value)
		_node.TotalSpentCents = value
	}
	if value, ok := wpc.mutation.Quantity(); ok {
		_spec.SetField(walletprojection.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := wpc.mutation.Unit(); ok {
		_spec.SetField(walletprojection.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := wpc.mutation.Reason(); ok {
		_spec.SetField(walletprojection.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := wpc.mutation.Result(); ok {
		_spec.SetField(walletprojection.FieldResult, field.TypeString, value)
		_node.Result = value
	}
	if value, ok := wpc.mutation.Source(); ok {
		_spec.SetField(walletprojection.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := wpc.mutation.Direction(); ok {
		_spec.SetField(walletprojection.FieldDirection, field.TypeString, value)
		_node.Direction = value
	}
	if value, ok := wpc.mutation.CreatedAt(); ok {
		_spec.SetField(walletprojection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wpc.mutation.UpdatedAt(); ok {
		_spec.SetField(walletprojection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := wpc.mutation.ArchivedAt(); ok {
		_spec.SetField(walletprojection.FieldArchivedAt, field.TypeTime, value)
		_node.ArchivedAt = &value
	}
	return _node, _spec
}

// WalletProjectionCreateBulk is the builder for creating many WalletProjection entities in bulk.
type WalletProjectionCreateBulk struct {
	config
	err      error
	builders []*WalletProjectionCreate
}

// Save creates the WalletProjection entities in the database.
func (wpcb *WalletProjectionCreateBulk) Save(ctx context.Context) ([]*WalletProjection, error) {
	if wpcb.err != nil {
		return nil, wpcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wpcb.builders))
	nodes := make([]*WalletProjection, len(wpcb.builders))
	mutators := make([]Mutator, len(wpcb.builders))
	for i := range wpcb.builders {
		func(i int, root context.Context) {
			builder := wpcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletProjectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wpcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wpcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wpcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wpcb *WalletProjectionCreateBulk) SaveX(ctx context.Context) []*WalletProjection {
	v, err := wpcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wpcb *WalletProjectionCreateBulk) Exec(ctx context.Context) error {
	_, err := wpcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wpcb *WalletProjectionCreateBulk) ExecX(ctx context.Context) {
	if err := wpcb.Exec(ctx); err != nil {
		panic(err)
	}
}
