// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"opl-cloud/services/control-plane/ent/predicate"
	"opl-cloud/services/control-plane/ent/workspace"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wu *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetAccountID sets the "account_id" field.
func (wu *WorkspaceUpdate) SetAccountID(s string) *WorkspaceUpdate {
	wu.mutation.SetAccountID(s)
	return wu
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableAccountID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetAccountID(*s)
	}
	return wu
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (wu *WorkspaceUpdate) SetOwnerAccountID(s string) *WorkspaceUpdate {
	wu.mutation.SetOwnerAccountID(s)
	return wu
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableOwnerAccountID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetOwnerAccountID(*s)
	}
	return wu
}

// SetOwnerUserID sets the "owner_user_id" field.
func (wu *WorkspaceUpdate) SetOwnerUserID(s string) *WorkspaceUpdate {
	wu.mutation.SetOwnerUserID(s)
	return wu
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableOwnerUserID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetOwnerUserID(*s)
	}
	return wu
}

// SetUserID sets the "user_id" field.
func (wu *WorkspaceUpdate) SetUserID(s string) *WorkspaceUpdate {
	wu.mutation.SetUserID(s)
	return wu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableUserID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetUserID(*s)
	}
	return wu
}

// SetEmail sets the "email" field.
func (wu *WorkspaceUpdate) SetEmail(s string) *WorkspaceUpdate {
	wu.mutation.SetEmail(s)
	return wu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableEmail(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetEmail(*s)
	}
	return wu
}

// SetRole sets the "role" field.
func (wu *WorkspaceUpdate) SetRole(s string) *WorkspaceUpdate {
	wu.mutation.SetRole(s)
	return wu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableRole(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetRole(*s)
	}
	return wu
}

// SetStatus sets the "status" field.
func (wu *WorkspaceUpdate) SetStatus(s string) *WorkspaceUpdate {
	wu.mutation.SetStatus(s)
	return wu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableStatus(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetStatus(*s)
	}
	return wu
}

// SetName sets the "name" field.
func (wu *WorkspaceUpdate) SetName(s string) *WorkspaceUpdate {
	wu.mutation.SetName(s)
	return wu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableName(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetName(*s)
	}
	return wu
}

// SetWorkspaceID sets the "workspace_id" field.
func (wu *WorkspaceUpdate) SetWorkspaceID(s string) *WorkspaceUpdate {
	wu.mutation.SetWorkspaceID(s)
	return wu
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableWorkspaceID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetWorkspaceID(*s)
	}
	return wu
}

// SetResourceID sets the "resource_id" field.
func (wu *WorkspaceUpdate) SetResourceID(s string) *WorkspaceUpdate {
	wu.mutation.SetResourceID(s)
	return wu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableResourceID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetResourceID(*s)
	}
	return wu
}

// SetResourceKind sets the "resource_kind" field.
func (wu *WorkspaceUpdate) SetResourceKind(s string) *WorkspaceUpdate {
	wu.mutation.SetResourceKind(s)
	return wu
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableResourceKind(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetResourceKind(*s)
	}
	return wu
}

// SetOperationID sets the "operation_id" field.
func (wu *WorkspaceUpdate) SetOperationID(s string) *WorkspaceUpdate {
	wu.mutation.SetOperationID(s)
	return wu
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableOperationID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetOperationID(*s)
	}
	return wu
}

// SetProvider sets the "provider" field.
func (wu *WorkspaceUpdate) SetProvider(s string) *WorkspaceUpdate {
	wu.mutation.SetProvider(s)
	return wu
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableProvider(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetProvider(*s)
	}
	return wu
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (wu *WorkspaceUpdate) SetProviderResourceID(s string) *WorkspaceUpdate {
	wu.mutation.SetProviderResourceID(s)
	return wu
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableProviderResourceID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetProviderResourceID(*s)
	}
	return wu
}

// SetURL sets the "url" field.
func (wu *WorkspaceUpdate) SetURL(s string) *WorkspaceUpdate {
	wu.mutation.SetURL(s)
	return wu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableURL(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetURL(*s)
	}
	return wu
}

// SetHoldID sets the "hold_id" field.
func (wu *WorkspaceUpdate) SetHoldID(s string) *WorkspaceUpdate {
	wu.mutation.SetHoldID(s)
	return wu
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableHoldID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetHoldID(*s)
	}
	return wu
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (wu *WorkspaceUpdate) SetHoldReleaseID(s string) *WorkspaceUpdate {
	wu.mutation.SetHoldReleaseID(s)
	return wu
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableHoldReleaseID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetHoldReleaseID(*s)
	}
	return wu
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (wu *WorkspaceUpdate) SetLedgerEntryID(s string) *WorkspaceUpdate {
	wu.mutation.SetLedgerEntryID(s)
	return wu
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableLedgerEntryID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetLedgerEntryID(*s)
	}
	return wu
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (wu *WorkspaceUpdate) SetWalletTransactionID(s string) *WorkspaceUpdate {
	wu.mutation.SetWalletTransactionID(s)
	return wu
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableWalletTransactionID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetWalletTransactionID(*s)
	}
	return wu
}

// SetSettlementID sets the "settlement_id" field.
func (wu *WorkspaceUpdate) SetSettlementID(s string) *WorkspaceUpdate {
	wu.mutation.SetSettlementID(s)
	return wu
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableSettlementID(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetSettlementID(*s)
	}
	return wu
}

// SetPricingVersion sets the "pricing_version" field.
func (wu *WorkspaceUpdate) SetPricingVersion(s string) *WorkspaceUpdate {
	wu.mutation.SetPricingVersion(s)
	return wu
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillablePricingVersion(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetPricingVersion(*s)
	}
	return wu
}

// SetAmountCents sets the "amount_cents" field.
func (wu *WorkspaceUpdate) SetAmountCents(i int64) *WorkspaceUpdate {
	wu.mutation.ResetAmountCents()
	wu.mutation.SetAmountCents(i)
	return wu
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableAmountCents(i *int64) *WorkspaceUpdate {
	if i != nil {
		wu.SetAmountCents(*i)
	}
	return wu
}

// AddAmountCents adds i to the "amount_cents" field.
func (wu *WorkspaceUpdate) AddAmountCents(i int64) *WorkspaceUpdate {
	wu.mutation.AddAmountCents(i)
	return wu
}

// SetBalanceCents sets the "balance_cents" field.
func (wu *WorkspaceUpdate) SetBalanceCents(i int64) *WorkspaceUpdate {
	wu.mutation.ResetBalanceCents()
	wu.mutation.SetBalanceCents(i)
	return wu
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableBalanceCents(i *int64) *WorkspaceUpdate {
	if i != nil {
		wu.SetBalanceCents(*i)
	}
	return wu
}

// AddBalanceCents adds i to the "balance_cents" field.
func (wu *WorkspaceUpdate) AddBalanceCents(i int64) *WorkspaceUpdate {
	wu.mutation.AddBalanceCents(i)
	return wu
}

// SetFrozenCents sets the "frozen_cents" field.
func (wu *WorkspaceUpdate) SetFrozenCents(i int64) *WorkspaceUpdate {
	wu.mutation.ResetFrozenCents()
	wu.mutation.SetFrozenCents(i)
	return wu
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableFrozenCents(i *int64) *WorkspaceUpdate {
	if i != nil {
		wu.SetFrozenCents(*i)
	}
	return wu
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (wu *WorkspaceUpdate) AddFrozenCents(i int64) *WorkspaceUpdate {
	wu.mutation.AddFrozenCents(i)
	return wu
}

// SetAvailableCents sets the "available_cents" field.
func (wu *WorkspaceUpdate) SetAvailableCents(i int64) *WorkspaceUpdate {
	wu.mutation.ResetAvailableCents()
	wu.mutation.SetAvailableCents(i)
	return wu
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableAvailableCents(i *int64) *WorkspaceUpdate {
	if i != nil {
		wu.SetAvailableCents(*i)
	}
	return wu
}

// AddAvailableCents adds i to the "available_cents" field.
func (wu *WorkspaceUpdate) AddAvailableCents(i int64) *WorkspaceUpdate {
	wu.mutation.AddAvailableCents(i)
	return wu
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (wu *WorkspaceUpdate) SetTotalSpentCents(i int64) *WorkspaceUpdate {
	wu.mutation.ResetTotalSpentCents()
	wu.mutation.SetTotalSpentCents(i)
	return wu
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableTotalSpentCents(i *int64) *WorkspaceUpdate {
	if i != nil {
		wu.SetTotalSpentCents(*i)
	}
	return wu
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (wu *WorkspaceUpdate) AddTotalSpentCents(i int64) *WorkspaceUpdate {
	wu.mutation.AddTotalSpentCents(i)
	return wu
}

// SetQuantity sets the "quantity" field.
func (wu *WorkspaceUpdate) SetQuantity(f float64) *WorkspaceUpdate {
	wu.mutation.ResetQuantity()
	wu.mutation.SetQuantity(f)
	return wu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableQuantity(f *float64) *WorkspaceUpdate {
	if f != nil {
		wu.SetQuantity(*f)
	}
	return wu
}

// AddQuantity adds f to the "quantity" field.
func (wu *WorkspaceUpdate) AddQuantity(f float64) *WorkspaceUpdate {
	wu.mutation.AddQuantity(f)
	return wu
}

// SetUnit sets the "unit" field.
func (wu *WorkspaceUpdate) SetUnit(s string) *WorkspaceUpdate {
	wu.mutation.SetUnit(s)
	return wu
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableUnit(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetUnit(*s)
	}
	return wu
}

// SetReason sets the "reason" field.
func (wu *WorkspaceUpdate) SetReason(s string) *WorkspaceUpdate {
	wu.mutation.SetReason(s)
	return wu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableReason(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetReason(*s)
	}
	return wu
}

// SetResult sets the "result" field.
func (wu *WorkspaceUpdate) SetResult(s string) *WorkspaceUpdate {
	wu.mutation.SetResult(s)
	return wu
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableResult(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetResult(*s)
	}
	return wu
}

// SetSource sets the "source" field.
func (wu *WorkspaceUpdate) SetSource(s string) *WorkspaceUpdate {
	wu.mutation.SetSource(s)
	return wu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableSource(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetSource(*s)
	}
	return wu
}

// SetDirection sets the "direction" field.
func (wu *WorkspaceUpdate) SetDirection(s string) *WorkspaceUpdate {
	wu.mutation.SetDirection(s)
	return wu
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableDirection(s *string) *WorkspaceUpdate {
	if s != nil {
		wu.SetDirection(*s)
	}
	return wu
}

// SetCreatedAt sets the "created_at" field.
func (wu *WorkspaceUpdate) SetCreatedAt(t time.Time) *WorkspaceUpdate {
	wu.mutation.SetCreatedAt(t)
	return wu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableCreatedAt(t *time.Time) *WorkspaceUpdate {
	if t != nil {
		wu.SetCreatedAt(*t)
	}
	return wu
}

// SetUpdatedAt sets the "updated_at" field.
func (wu *WorkspaceUpdate) SetUpdatedAt(t time.Time) *WorkspaceUpdate {
	wu.mutation.SetUpdatedAt(t)
	return wu
}

// SetArchivedAt sets the "archived_at" field.
func (wu *WorkspaceUpdate) SetArchivedAt(t time.Time) *WorkspaceUpdate {
	wu.mutation.SetArchivedAt(t)
	return wu
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (wu *WorkspaceUpdate) SetNillableArchivedAt(t *time.Time) *WorkspaceUpdate {
	if t != nil {
		wu.SetArchivedAt(*t)
	}
	return wu
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (wu *WorkspaceUpdate) ClearArchivedAt() *WorkspaceUpdate {
	wu.mutation.ClearArchivedAt()
	return wu
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wu *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return wu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	wu.defaults()
	return withHooks(ctx, wu.sqlSave, wu.mutation, wu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wu *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wu *WorkspaceUpdate) defaults() {
	if _, ok := wu.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		wu.mutation.SetUpdatedAt(v)
	}
}

func (wu *WorkspaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.AccountID(); ok {
		_spec.SetField(workspace.FieldAccountID, field.TypeString, value)
	}
	if value, ok := wu.mutation.OwnerAccountID(); ok {
		_spec.SetField(workspace.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := wu.mutation.OwnerUserID(); ok {
		_spec.SetField(workspace.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := wu.mutation.UserID(); ok {
		_spec.SetField(workspace.FieldUserID, field.TypeString, value)
	}
	if value, ok := wu.mutation.Email(); ok {
		_spec.SetField(workspace.FieldEmail, field.TypeString, value)
	}
	if value, ok := wu.mutation.Role(); ok {
		_spec.SetField(workspace.FieldRole, field.TypeString, value)
	}
	if value, ok := wu.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := wu.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wu.mutation.WorkspaceID(); ok {
		_spec.SetField(workspace.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := wu.mutation.ResourceID(); ok {
		_spec.SetField(workspace.FieldResourceID, field.TypeString, value)
	}
	if value, ok := wu.mutation.ResourceKind(); ok {
		_spec.SetField(workspace.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := wu.mutation.OperationID(); ok {
		_spec.SetField(workspace.FieldOperationID, field.TypeString, value)
	}
	if value, ok := wu.mutation.Provider(); ok {
		_spec.SetField(workspace.FieldProvider, field.TypeString, value)
	}
	if value, ok := wu.mutation.ProviderResourceID(); ok {
		_spec.SetField(workspace.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := wu.mutation.URL(); ok {
		_spec.SetField(workspace.FieldURL, field.TypeString, value)
	}
	if value, ok := wu.mutation.HoldID(); ok {
		_spec.SetField(workspace.FieldHoldID, field.TypeString, value)
	}
	if value, ok := wu.mutation.HoldReleaseID(); ok {
		_spec.SetField(workspace.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := wu.mutation.LedgerEntryID(); ok {
		_spec.SetField(workspace.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := wu.mutation.WalletTransactionID(); ok {
		_spec.SetField(workspace.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := wu.mutation.SettlementID(); ok {
		_spec.SetField(workspace.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := wu.mutation.PricingVersion(); ok {
		_spec.SetField(workspace.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := wu.mutation.AmountCents(); ok {
		_spec.SetField(workspace.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedAmountCents(); ok {
		_spec.AddField(workspace.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.BalanceCents(); ok {
		_spec.SetField(workspace.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedBalanceCents(); ok {
		_spec.AddField(workspace.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.FrozenCents(); ok {
		_spec.SetField(workspace.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedFrozenCents(); ok {
		_spec.AddField(workspace.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AvailableCents(); ok {
		_spec.SetField(workspace.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedAvailableCents(); ok {
		_spec.AddField(workspace.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.TotalSpentCents(); ok {
		_spec.SetField(workspace.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(workspace.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wu.mutation.Quantity(); ok {
		_spec.SetField(workspace.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := wu.mutation.AddedQuantity(); ok {
		_spec.AddField(workspace.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := wu.mutation.Unit(); ok {
		_spec.SetField(workspace.FieldUnit, field.TypeString, value)
	}
	if value, ok := wu.mutation.Reason(); ok {
		_spec.SetField(workspace.FieldReason, field.TypeString, value)
	}
	if value, ok := wu.mutation.Result(); ok {
		_spec.SetField(workspace.FieldResult, field.TypeString, value)
	}
	if value, ok := wu.mutation.Source(); ok {
		_spec.SetField(workspace.FieldSource, field.TypeString, value)
	}
	if value, ok := wu.mutation.Direction(); ok {
		_spec.SetField(workspace.FieldDirection, field.TypeString, value)
	}
	if value, ok := wu.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wu.mutation.ArchivedAt(); ok {
		_spec.SetField(workspace.FieldArchivedAt, field.TypeTime, value)
	}
	if wu.mutation.ArchivedAtCleared() {
		_spec.ClearField(workspace.FieldArchivedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wu.mutation.done = true
	return n, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetAccountID sets the "account_id" field.
func (wuo *WorkspaceUpdateOne) SetAccountID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetAccountID(s)
	return wuo
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableAccountID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetAccountID(*s)
	}
	return wuo
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (wuo *WorkspaceUpdateOne) SetOwnerAccountID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetOwnerAccountID(s)
	return wuo
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableOwnerAccountID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetOwnerAccountID(*s)
	}
	return wuo
}

// SetOwnerUserID sets the "owner_user_id" field.
func (wuo *WorkspaceUpdateOne) SetOwnerUserID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetOwnerUserID(s)
	return wuo
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableOwnerUserID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetOwnerUserID(*s)
	}
	return wuo
}

// SetUserID sets the "user_id" field.
func (wuo *WorkspaceUpdateOne) SetUserID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetUserID(s)
	return wuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableUserID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetUserID(*s)
	}
	return wuo
}

// SetEmail sets the "email" field.
func (wuo *WorkspaceUpdateOne) SetEmail(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetEmail(s)
	return wuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableEmail(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetEmail(*s)
	}
	return wuo
}

// SetRole sets the "role" field.
func (wuo *WorkspaceUpdateOne) SetRole(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetRole(s)
	return wuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableRole(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetRole(*s)
	}
	return wuo
}

// SetStatus sets the "status" field.
func (wuo *WorkspaceUpdateOne) SetStatus(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetStatus(s)
	return wuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableStatus(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetStatus(*s)
	}
	return wuo
}

// SetName sets the "name" field.
func (wuo *WorkspaceUpdateOne) SetName(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetName(s)
	return wuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableName(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetName(*s)
	}
	return wuo
}

// SetWorkspaceID sets the "workspace_id" field.
func (wuo *WorkspaceUpdateOne) SetWorkspaceID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetWorkspaceID(s)
	return wuo
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableWorkspaceID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetWorkspaceID(*s)
	}
	return wuo
}

// SetResourceID sets the "resource_id" field.
func (wuo *WorkspaceUpdateOne) SetResourceID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetResourceID(s)
	return wuo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableResourceID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetResourceID(*s)
	}
	return wuo
}

// SetResourceKind sets the "resource_kind" field.
func (wuo *WorkspaceUpdateOne) SetResourceKind(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetResourceKind(s)
	return wuo
}

// SetNillableResourceKind sets the "resource_kind" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableResourceKind(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetResourceKind(*s)
	}
	return wuo
}

// SetOperationID sets the "operation_id" field.
func (wuo *WorkspaceUpdateOne) SetOperationID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetOperationID(s)
	return wuo
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableOperationID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetOperationID(*s)
	}
	return wuo
}

// SetProvider sets the "provider" field.
func (wuo *WorkspaceUpdateOne) SetProvider(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetProvider(s)
	return wuo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableProvider(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetProvider(*s)
	}
	return wuo
}

// SetProviderResourceID sets the "provider_resource_id" field.
func (wuo *WorkspaceUpdateOne) SetProviderResourceID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetProviderResourceID(s)
	return wuo
}

// SetNillableProviderResourceID sets the "provider_resource_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableProviderResourceID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetProviderResourceID(*s)
	}
	return wuo
}

// SetURL sets the "url" field.
func (wuo *WorkspaceUpdateOne) SetURL(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetURL(s)
	return wuo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableURL(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetURL(*s)
	}
	return wuo
}

// SetHoldID sets the "hold_id" field.
func (wuo *WorkspaceUpdateOne) SetHoldID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetHoldID(s)
	return wuo
}

// SetNillableHoldID sets the "hold_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableHoldID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetHoldID(*s)
	}
	return wuo
}

// SetHoldReleaseID sets the "hold_release_id" field.
func (wuo *WorkspaceUpdateOne) SetHoldReleaseID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetHoldReleaseID(s)
	return wuo
}

// SetNillableHoldReleaseID sets the "hold_release_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableHoldReleaseID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetHoldReleaseID(*s)
	}
	return wuo
}

// SetLedgerEntryID sets the "ledger_entry_id" field.
func (wuo *WorkspaceUpdateOne) SetLedgerEntryID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetLedgerEntryID(s)
	return wuo
}

// SetNillableLedgerEntryID sets the "ledger_entry_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableLedgerEntryID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetLedgerEntryID(*s)
	}
	return wuo
}

// SetWalletTransactionID sets the "wallet_transaction_id" field.
func (wuo *WorkspaceUpdateOne) SetWalletTransactionID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetWalletTransactionID(s)
	return wuo
}

// SetNillableWalletTransactionID sets the "wallet_transaction_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableWalletTransactionID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetWalletTransactionID(*s)
	}
	return wuo
}

// SetSettlementID sets the "settlement_id" field.
func (wuo *WorkspaceUpdateOne) SetSettlementID(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetSettlementID(s)
	return wuo
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableSettlementID(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetSettlementID(*s)
	}
	return wuo
}

// SetPricingVersion sets the "pricing_version" field.
func (wuo *WorkspaceUpdateOne) SetPricingVersion(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetPricingVersion(s)
	return wuo
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillablePricingVersion(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetPricingVersion(*s)
	}
	return wuo
}

// SetAmountCents sets the "amount_cents" field.
func (wuo *WorkspaceUpdateOne) SetAmountCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.ResetAmountCents()
	wuo.mutation.SetAmountCents(i)
	return wuo
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableAmountCents(i *int64) *WorkspaceUpdateOne {
	if i != nil {
		wuo.SetAmountCents(*i)
	}
	return wuo
}

// AddAmountCents adds i to the "amount_cents" field.
func (wuo *WorkspaceUpdateOne) AddAmountCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.AddAmountCents(i)
	return wuo
}

// SetBalanceCents sets the "balance_cents" field.
func (wuo *WorkspaceUpdateOne) SetBalanceCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.ResetBalanceCents()
	wuo.mutation.SetBalanceCents(i)
	return wuo
}

// SetNillableBalanceCents sets the "balance_cents" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableBalanceCents(i *int64) *WorkspaceUpdateOne {
	if i != nil {
		wuo.SetBalanceCents(*i)
	}
	return wuo
}

// AddBalanceCents adds i to the "balance_cents" field.
func (wuo *WorkspaceUpdateOne) AddBalanceCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.AddBalanceCents(i)
	return wuo
}

// SetFrozenCents sets the "frozen_cents" field.
func (wuo *WorkspaceUpdateOne) SetFrozenCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.ResetFrozenCents()
	wuo.mutation.SetFrozenCents(i)
	return wuo
}

// SetNillableFrozenCents sets the "frozen_cents" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableFrozenCents(i *int64) *WorkspaceUpdateOne {
	if i != nil {
		wuo.SetFrozenCents(*i)
	}
	return wuo
}

// AddFrozenCents adds i to the "frozen_cents" field.
func (wuo *WorkspaceUpdateOne) AddFrozenCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.AddFrozenCents(i)
	return wuo
}

// SetAvailableCents sets the "available_cents" field.
func (wuo *WorkspaceUpdateOne) SetAvailableCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.ResetAvailableCents()
	wuo.mutation.SetAvailableCents(i)
	return wuo
}

// SetNillableAvailableCents sets the "available_cents" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableAvailableCents(i *int64) *WorkspaceUpdateOne {
	if i != nil {
		wuo.SetAvailableCents(*i)
	}
	return wuo
}

// AddAvailableCents adds i to the "available_cents" field.
func (wuo *WorkspaceUpdateOne) AddAvailableCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.AddAvailableCents(i)
	return wuo
}

// SetTotalSpentCents sets the "total_spent_cents" field.
func (wuo *WorkspaceUpdateOne) SetTotalSpentCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.ResetTotalSpentCents()
	wuo.mutation.SetTotalSpentCents(i)
	return wuo
}

// SetNillableTotalSpentCents sets the "total_spent_cents" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableTotalSpentCents(i *int64) *WorkspaceUpdateOne {
	if i != nil {
		wuo.SetTotalSpentCents(*i)
	}
	return wuo
}

// AddTotalSpentCents adds i to the "total_spent_cents" field.
func (wuo *WorkspaceUpdateOne) AddTotalSpentCents(i int64) *WorkspaceUpdateOne {
	wuo.mutation.AddTotalSpentCents(i)
	return wuo
}

// SetQuantity sets the "quantity" field.
func (wuo *WorkspaceUpdateOne) SetQuantity(f float64) *WorkspaceUpdateOne {
	wuo.mutation.ResetQuantity()
	wuo.mutation.SetQuantity(f)
	return wuo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableQuantity(f *float64) *WorkspaceUpdateOne {
	if f != nil {
		wuo.SetQuantity(*f)
	}
	return wuo
}

// AddQuantity adds f to the "quantity" field.
func (wuo *WorkspaceUpdateOne) AddQuantity(f float64) *WorkspaceUpdateOne {
	wuo.mutation.AddQuantity(f)
	return wuo
}

// SetUnit sets the "unit" field.
func (wuo *WorkspaceUpdateOne) SetUnit(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetUnit(s)
	return wuo
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableUnit(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetUnit(*s)
	}
	return wuo
}

// SetReason sets the "reason" field.
func (wuo *WorkspaceUpdateOne) SetReason(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetReason(s)
	return wuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableReason(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetReason(*s)
	}
	return wuo
}

// SetResult sets the "result" field.
func (wuo *WorkspaceUpdateOne) SetResult(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetResult(s)
	return wuo
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableResult(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetResult(*s)
	}
	return wuo
}

// SetSource sets the "source" field.
func (wuo *WorkspaceUpdateOne) SetSource(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetSource(s)
	return wuo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableSource(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetSource(*s)
	}
	return wuo
}

// SetDirection sets the "direction" field.
func (wuo *WorkspaceUpdateOne) SetDirection(s string) *WorkspaceUpdateOne {
	wuo.mutation.SetDirection(s)
	return wuo
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableDirection(s *string) *WorkspaceUpdateOne {
	if s != nil {
		wuo.SetDirection(*s)
	}
	return wuo
}

// SetCreatedAt sets the "created_at" field.
func (wuo *WorkspaceUpdateOne) SetCreatedAt(t time.Time) *WorkspaceUpdateOne {
	wuo.mutation.SetCreatedAt(t)
	return wuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableCreatedAt(t *time.Time) *WorkspaceUpdateOne {
	if t != nil {
		wuo.SetCreatedAt(*t)
	}
	return wuo
}

// SetUpdatedAt sets the "updated_at" field.
func (wuo *WorkspaceUpdateOne) SetUpdatedAt(t time.Time) *WorkspaceUpdateOne {
	wuo.mutation.SetUpdatedAt(t)
	return wuo
}

// SetArchivedAt sets the "archived_at" field.
func (wuo *WorkspaceUpdateOne) SetArchivedAt(t time.Time) *WorkspaceUpdateOne {
	wuo.mutation.SetArchivedAt(t)
	return wuo
}

// SetNillableArchivedAt sets the "archived_at" field if the given value is not nil.
func (wuo *WorkspaceUpdateOne) SetNillableArchivedAt(t *time.Time) *WorkspaceUpdateOne {
	if t != nil {
		wuo.SetArchivedAt(*t)
	}
	return wuo
}

// ClearArchivedAt clears the value of the "archived_at" field.
func (wuo *WorkspaceUpdateOne) ClearArchivedAt() *WorkspaceUpdateOne {
	wuo.mutation.ClearArchivedAt()
	return wuo
}

// Mutation returns the WorkspaceMutation object of the builder.
func (wuo *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return wuo.mutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (wuo *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	wuo.mutation.Where(ps...)
	return wuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Workspace entity.
func (wuo *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	wuo.defaults()
	return withHooks(ctx, wuo.sqlSave, wuo.mutation, wuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wuo *WorkspaceUpdateOne) defaults() {
	if _, ok := wuo.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		wuo.mutation.SetUpdatedAt(v)
	}
}

func (wuo *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeString))
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.AccountID(); ok {
		_spec.SetField(workspace.FieldAccountID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.OwnerAccountID(); ok {
		_spec.SetField(workspace.FieldOwnerAccountID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.OwnerUserID(); ok {
		_spec.SetField(workspace.FieldOwnerUserID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.UserID(); ok {
		_spec.SetField(workspace.FieldUserID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Email(); ok {
		_spec.SetField(workspace.FieldEmail, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Role(); ok {
		_spec.SetField(workspace.FieldRole, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Status(); ok {
		_spec.SetField(workspace.FieldStatus, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := wuo.mutation.WorkspaceID(); ok {
		_spec.SetField(workspace.FieldWorkspaceID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.ResourceID(); ok {
		_spec.SetField(workspace.FieldResourceID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.ResourceKind(); ok {
		_spec.SetField(workspace.FieldResourceKind, field.TypeString, value)
	}
	if value, ok := wuo.mutation.OperationID(); ok {
		_spec.SetField(workspace.FieldOperationID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Provider(); ok {
		_spec.SetField(workspace.FieldProvider, field.TypeString, value)
	}
	if value, ok := wuo.mutation.ProviderResourceID(); ok {
		_spec.SetField(workspace.FieldProviderResourceID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.URL(); ok {
		_spec.SetField(workspace.FieldURL, field.TypeString, value)
	}
	if value, ok := wuo.mutation.HoldID(); ok {
		_spec.SetField(workspace.FieldHoldID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.HoldReleaseID(); ok {
		_spec.SetField(workspace.FieldHoldReleaseID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.LedgerEntryID(); ok {
		_spec.SetField(workspace.FieldLedgerEntryID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.WalletTransactionID(); ok {
		_spec.SetField(workspace.FieldWalletTransactionID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.SettlementID(); ok {
		_spec.SetField(workspace.FieldSettlementID, field.TypeString, value)
	}
	if value, ok := wuo.mutation.PricingVersion(); ok {
		_spec.SetField(workspace.FieldPricingVersion, field.TypeString, value)
	}
	if value, ok := wuo.mutation.AmountCents(); ok {
		_spec.SetField(workspace.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedAmountCents(); ok {
		_spec.AddField(workspace.FieldAmountCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.BalanceCents(); ok {
		_spec.SetField(workspace.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedBalanceCents(); ok {
		_spec.AddField(workspace.FieldBalanceCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.FrozenCents(); ok {
		_spec.SetField(workspace.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedFrozenCents(); ok {
		_spec.AddField(workspace.FieldFrozenCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AvailableCents(); ok {
		_spec.SetField(workspace.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedAvailableCents(); ok {
		_spec.AddField(workspace.FieldAvailableCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.TotalSpentCents(); ok {
		_spec.SetField(workspace.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.AddedTotalSpentCents(); ok {
		_spec.AddField(workspace.FieldTotalSpentCents, field.TypeInt64, value)
	}
	if value, ok := wuo.mutation.Quantity(); ok {
		_spec.SetField(workspace.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := wuo.mutation.AddedQuantity(); ok {
		_spec.AddField(workspace.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := wuo.mutation.Unit(); ok {
		_spec.SetField(workspace.FieldUnit, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Reason(); ok {
		_spec.SetField(workspace.FieldReason, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Result(); ok {
		_spec.SetField(workspace.FieldResult, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Source(); ok {
		_spec.SetField(workspace.FieldSource, field.TypeString, value)
	}
	if value, ok := wuo.mutation.Direction(); ok {
		_spec.SetField(workspace.FieldDirection, field.TypeString, value)
	}
	if value, ok := wuo.mutation.CreatedAt(); ok {
		_spec.SetField(workspace.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wuo.mutation.ArchivedAt(); ok {
		_spec.SetField(workspace.FieldArchivedAt, field.TypeTime, value)
	}
	if wuo.mutation.ArchivedAtCleared() {
		_spec.ClearField(workspace.FieldArchivedAt, field.TypeTime)
	}
	_node = &Workspace{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wuo.mutation.done = true
	return _node, nil
}
