CREATE TABLE IF NOT EXISTS control_plane_accounts (id TEXT PRIMARY KEY, account_id TEXT NOT NULL DEFAULT '', owner_account_id TEXT NOT NULL DEFAULT '', owner_user_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT '', name TEXT NOT NULL DEFAULT '', workspace_id TEXT NOT NULL DEFAULT '', resource_id TEXT NOT NULL DEFAULT '', resource_kind TEXT NOT NULL DEFAULT '', operation_id TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', provider_resource_id TEXT NOT NULL DEFAULT '', url TEXT NOT NULL DEFAULT '', hold_id TEXT NOT NULL DEFAULT '', hold_release_id TEXT NOT NULL DEFAULT '', ledger_entry_id TEXT NOT NULL DEFAULT '', wallet_transaction_id TEXT NOT NULL DEFAULT '', settlement_id TEXT NOT NULL DEFAULT '', pricing_version TEXT NOT NULL DEFAULT '', amount_cents BIGINT NOT NULL DEFAULT 0, balance_cents BIGINT NOT NULL DEFAULT 0, frozen_cents BIGINT NOT NULL DEFAULT 0, available_cents BIGINT NOT NULL DEFAULT 0, total_spent_cents BIGINT NOT NULL DEFAULT 0, quantity DOUBLE PRECISION NOT NULL DEFAULT 0, unit TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', source TEXT NOT NULL DEFAULT '', direction TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), archived_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS control_plane_users (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_organizations (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_memberships (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_sessions (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_auth_attempts (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_compute_allocations (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_storage_volumes (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_storage_attachments (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_workspaces (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_wallet_projections (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_ledger_projections (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_wallet_transaction_projections (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_manual_topup_projections (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_billing_reconciliation (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_runtime_operations (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_admin_audit_events (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_support_ticket_mappings (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_production_e2e_records (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archive_jobs (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archived_compute_allocations (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archived_storage_volumes (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archived_storage_attachments (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archived_workspaces (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);
CREATE TABLE IF NOT EXISTS control_plane_archived_admin_audit_events (LIKE control_plane_accounts INCLUDING DEFAULTS INCLUDING CONSTRAINTS);

CREATE INDEX IF NOT EXISTS control_plane_compute_allocations_account_idx ON control_plane_compute_allocations(account_id);
CREATE INDEX IF NOT EXISTS control_plane_storage_volumes_account_idx ON control_plane_storage_volumes(account_id);
CREATE INDEX IF NOT EXISTS control_plane_workspaces_account_idx ON control_plane_workspaces(account_id);
CREATE INDEX IF NOT EXISTS control_plane_admin_audit_events_account_idx ON control_plane_admin_audit_events(account_id);
